### ISSUE TITLE
Animation Misbeahaviour

### ISSUE THREAD

**Issue by m8r1x** [jgthms/bulma#1025]
I have this `ball-grid-beat` animation that I'm trying to implement in `react v0.15.4` which works as expected. However when I add the link tag to bulma cdn
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.0/css/bulma.min.css">`
 the animation freaks out and starts spinning. Here's the animation code.
```css
/* style.css */

/*This is the animation bit*/
.loader {
	box-sizing: border-box;
	display: flex;
	flex: 0 1 auto;
	flex-direction: column;
	flex-grow: 1;
	flex-shrink: 0;
	flex-basis: 25%;
	max-width: 25%;
	height: 200px;
	align-items: center;
	justify-content: center;
}

@keyframes ball-grid-beat {
  50% {
    opacity: 0.7;
  }
  100% {
    opacity: 1;
  }
}

@-webkit-keyframes ball-grid-beat {
  50% {
    opacity: 0.7;
  }
  100% {
    opacity: 1;
  }
}

.ball-grid-beat {
  width: 57px;
}

.ball-grid-beat > div:nth-child(1) {
  animation-delay: 0.79s;
  -webkit-animation-delay: 0.79s;
  animation-duration: 1s;
  -webkit-animation-duration: 1s;
}

.ball-grid-beat > div:nth-child(2) {
  animation-delay: 0.24s;
  -webkit-animation-delay: 0.24s;
  animation-duration: 1.19s;
  -webkit-animation-duration: 1.19s;
}

.ball-grid-beat > div:nth-child(3) {
  animation-delay: 0.31s;
  -webkit-animation-delay: 0.31s;
  animation-duration: 1.46s;
  -webkit-animation-duration: 1.46s;
}

.ball-grid-beat > div:nth-child(4) {
  animation-delay: 0.32s;
  -webkit-animation-delay: 0.32s;
  animation-duration: 0.77s;
  -webkit-animation-duration: 0.77s;
}

.ball-grid-beat > div:nth-child(5) {
  animation-delay: 0.29s;
  -webkit-animation-delay: 0.29s;
  animation-duration: 1.45s;
  -webkit-animation-duration: 1.45s;
}

.ball-grid-beat > div:nth-child(6) {
  animation-delay: 0.55s;
  -webkit-animation-delay: 0.55s;
  animation-duration: 1.53s;
  -webkit-animation-duration: 1.53s;
}

.ball-grid-beat > div:nth-child(7) {
  animation-delay: 0.11s;
  -webkit-animation-delay: 0.11s;
  animation-duration: 1.38s;
  -webkit-animation-duration: 1.38s;
}

.ball-grid-beat > div:nth-child(8) {
  animation-delay: 0.18s;
  -webkit-animation-delay: 0.18s;
  animation-duration: 1.54s;
  -webkit-animation-duration: 1.54s;
}

.ball-grid-beat > div:nth-child(9) {
  animation-delay: 0.1s;
  -webkit-animation-delay: 0.1s;
  animation-duration: 0.94s;
  -webkit-animation-duration: 0.94s;
}

.ball-grid-beat > div {
  background-color: #FF1E91;
  width: 15px;
  height: 15px;
  border-radius: 100%;
  margin: 2px;
  animation-fill-mode: both;
  display: inline-block;
  float: left;
  animation-name: ball-grid-beat;
  -webkit-animation-name: ball-grid-beat;
  animation-iteration-count: infinite;
  -webkit-animation-iteration-count: infinite;
  animation-delay: 0;
  -webkit-animation-delay: 0;
}

```

and in 
```javascript
// App.js

const App = () => (
    <div className="loader">
        <div className="ball-grid-beat">
            { ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine'].map(ele => <div key={ele} />)}
        </div>
    </div>
)

export default App
```

I have no idea what I'm doing wrong. Any help would greately be appreciated.
