### ISSUE TITLE
Nested Colums

### ISSUE THREAD

**Issue by olien** [jgthms/bulma#118]
Hi,

is it possible to make nested colums like this:

**Desktop**

| - 3 -  ||  - 3 - | | ----- 6 ----- |

**Tablet**

| - 3 - | |----- 9 -----| 
| - 3 - | 

(col "9" with same height like the other ones together)

**Mobile** 

|  - 12 -  |
|  - 12 -  |
|  - 12 -  |

or

| - 6 - || - 6 - | 
|----- 12 -----| 

BR
Oliver

**Comment by ncksllvn** [comment]
I feel like the documentation does a really good job covering [the grid](http://bulma.io/documentation/grid/). All of that is definitely possible.

**Comment by gabsprates** [comment]
Hi, I belive with Bulma's grid, isn't possible do this, but I try make an exemple with what i understand you want.
http://codepen.io/gabsprates/pen/zqKRML

Just create the `.is-double-half-tablet`, with `flex-basis: 66.6666%;`, on `@media (min-width: 769px) and (max-width: 979px)`, and add to the second div.

**Comment by gabsprates** [comment]
Hi @olien , try this:
```html
<div id="box" class="columns">
  <div class="column columns is-mobile is-half-desktop is-third-tablet">
    <div class="column">1</div>
    <div class="column">2</div>
  </div>
  <div class="column">3</div>
</div>
```
```css
.columns {
  margin: 0;
  padding: 0;
  text-align: center;
}
.column {
  &.columns {
    margin: 0;
    .column {
      flex-basis: 100%;
    }
    @media (min-width: 769px) and (max-width: 979px) {
      flex-wrap: wrap;
    }
  }
}
```
Can you see here:
http://codepen.io/gabsprates/pen/zqKRML
