### ISSUE TITLE
Introduce a new helper class for text overflow

### ISSUE THREAD

**Issue by iamazik** [jgthms/bulma#1188]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.5.1
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Description

While working with Bulma today, I had to use to `text-overflow` CSS property to ensure the sentence remains in one line and don't push other elements. However, I couldn't find a helper class that would help me to do this. So, I thought why not to submit a feature request for a new helper class `is-text-overflow`.

### Example
```css
.is-text-overflow {
    flex: 1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

More information can be found [here](https://css-tricks.com/flexbox-truncated-text/).
