### ISSUE TITLE
Navbar background color not fully applied to "navbar-end" > "navbar-item has-dropdown" without "is-active"

### ISSUE THREAD

**Issue by dgilland** [jgthms/bulma#1330]
### Overview of the problem

This is about the Bulma **CSS framework**
Is it a bug/feature/question or do you need help? **bug**
I'm using Bulma **version** [0.6.0]
My **browser** is: Chrome
I am sure this issue is **not a duplicate**? Yes

### Description

When using a navbar background color like `<nav class="navbar is-dark">` that includes a `.navbar-end` with `.navbar-item.has-dropdown` that **doesn't** include `.is-active`, the background color of the `.navbar-item` is not fully "extended" over the element.

### Steps to Reproduce

The following HTML produces the issue:

```html
<body>
  <div class="container">
    <nav class="navbar is-dark">
      <div class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item has-dropdown">
            <a class="navbar-link">Right</a>
          </div>
        </div>
      </div>
    </nav>
  </div>
</body>
```

When you hover over the dropdown, the right side background color is extended to include the entire `navbar-item`.

### Expected behavior

Navbar should look like this:

![image](https://user-images.githubusercontent.com/1251349/31727347-5885aede-b3f7-11e7-950f-2689ad15ce62.png)

### Actual behavior

Navbar appears cut-off:

![image](https://user-images.githubusercontent.com/1251349/31727301-3c252c74-b3f7-11e7-801f-f667dc93b874.png)

Currently, I'm using the following CSS to workaround the issue which results in the expected behavior above:

```css
.navbar.is-dark .navbar-end .navbar-item.has-dropdown {
  background-color: #363636;
}
```

**Comment by rafaelrenanpacheco** [comment]
The following CSS caused this problem:

```css
@media screen and (min-width: 1024px)
.container>.navbar .navbar-menu {
    margin-right: -1rem;
}
```

I don't know why this rule exists, because deleting it will fix the problem. To test, go to https://jsfiddle.net/8mfweL4f/ and inspect the `navbar-menu` to disable this rule.

**Comment by dgilland** [comment]
I can confirm that adding the following CSS to disable the `margin-right: -1rem;` rule per @rafaelrenanpacheco's suggestion fixes the issue:

```css
.container > .navbar .navbar-menu {
  margin-right: 0px;
}
```

**Comment by dgilland** [comment]
Actually, it looks like there's a corresponding `margin-left: -1rem;` that's set on `.navbar-brand`:

```css
@media screen and (min-width: 1024px)
.container > .navbar .navbar-brand {
    margin-left: -1rem;
}
```

which results in a misspaced navbar when just remove the `margin-right` from `.container > .navbar .navbar-menu` in https://github.com/jgthms/bulma/issues/1330#issuecomment-337781522:

![image](https://user-images.githubusercontent.com/1251349/31753110-9ee02304-b45c-11e7-94a0-2d8a3a8a1a86.png)

So to balance out the navbar using the margin fix approach would require:

```css
.container > .navbar .navbar-brand {
  margin-left: 0px;
}
.container > .navbar .navbar-menu {
  margin-right: 0px;
}
```

But perhaps there's a better solution that keeps the margin offsets if those are serving a purpose in the overall navbar design.
