### ISSUE TITLE
Why does is-gapless control width?

### ISSUE THREAD

**Issue by stavlocker** [jgthms/bulma#1370]
This is a bug/question about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.0
I am sure this issue is **not a duplicate**.

### Description

I've noticed that `is-gapless` forcefully sets it's column children's paddings to `0 !important` (😱). But why is it like this? The `is-gapless` class should just make it's children not have gaps by setting the margin to 0, which it does. But why does it forcefully control the padding? Is this a bug? It seems more reasonable to me that the margin should've been !important rather than the padding.

If there's a reason, what is it? And why isn't it in the docs?

### Expected Behaviour
```css
.columns.is-gapless > .column {
    margin: 0 !important; /*Could be non-important, it's arguable*/
}
```

### Actual Behaviour
```css
.columns.is-gapless > .column {
    padding: 0 !important;
    margin: 0;
}
```
