### ISSUE TITLE
Reuse navbar-fixed-z variable gives compilation error

### ISSUE THREAD

**Issue by mikaelharsjo** [jgthms/bulma#1470]
This is a question about Bulma.

### Overview of the problem

I'm using Bulma **version** 0.6.1.
I have a small issue with the fixed navbar.
I'm trying to reuse the `z-index` of the navbar in my own sass files.
```css
@import './node_modules/bulma/sass/utilities/initial-variables';
 
.subNav {
  z-index: $navbar-fixed-z;
}
```
But get a compilation error like:
`Undefined variable: "$navbar-fixed-z"`

I know this customisation is not documented but I see no difference between this variable and others.
