### ISSUE TITLE
Add .is-darker and .is-lighter

### ISSUE THREAD

**Issue by jbrooksuk** [jgthms/bulma#155]
These two classes would be used to gently lighten a colour, similar to how `.is-bold` adds a gradient.

Going a step further, you could add steps for `.is-darker-1` to `.is-darker-10` which would work on a scale of 10% steps?

**Comment by TroyAlford** [comment]
How would you apply this on a per-color basis? It seems to imply that you'd have # of colors x # of steps variations - is there a use-case you can see for that?

To me, an individual implementer would be better served by using `$blue` for example, and then adding `$blue-lighter-1` or `$blue-darker-1`.

**Comment by jbrooksuk** [comment]
(Note that I'm using Bulma in a SCSS project, so the syntax is a little different).

I added the following:

```scss
.hero {
    @each $name, $pair in $colors {
        $color: nth($pair, 1);
        $color-invert: nth($pair, 2);
        &.is-#{$name} {
            &.is-lighter {
                background: lighten($color, 5%);
                color: $color-invert;

                strong {
                    color: $color-invert;
                }
            }
            &.is-darker {
                background: darken($color, 10%);
                color: $color-invert;

                strong {
                    color: $color-invert;
                }
            }
            &.is-inverted {
                background: $color-invert;
                color: $color;
            }
        }
    }
}
```
