### ISSUE TITLE
[ FIX] Select with Select2

### ISSUE THREAD

**Issue by Thadeu** [jgthms/bulma#1555]
I did need use select2 in my project, so fixed select2 following below code.
I worked with rails, e.g

```erb
<div class="column">
  <%= f.label :role_id, 'Perfil', class: 'label' %>
  <div class="field">
    <div class="control">
      <%= f.collection_select :role_id,
          Role.all,
          :id, 
          :name,
          {selected: @resource.role_id, include_blank: true}, 
          {required: false, class: '' }
      %>
    </div>
  </div>
</div>
```

### bulma.select2.custom.scss

```scss
.select2-container {
  .select2-selection--single {
    height: auto !important;
    padding: 3px 0 !important;
    border: 1px solid #dbdbdb !important;

    .select2-selection__arrow{
      top: 5px !important;
    }

    .select2-selection__placeholder {
      color: #dbdbdb !important;
    }
  }

  .select2-dropdown {
    border: 1px solid #dbdbdb !important;
    border-top: 0 !important;

    .select2-search {
      margin: 5px;

      .select2-search__field {
        padding: 10px !important;
        border-radius: 3px !important;
        font-size: 1rem;
        height: 2.25em;
        box-shadow: inset 0 1px 2px rgba(10,10,10,.1);
        max-width: 100%;
        width: 100%;
        border-radius: 3px !important;
      }
    }
    
    .select2-results__options {
      max-height: 200px !important;

      .select2-results__option {
        padding: 0.37em 0.75em !important;
        font-size: 1rem;
        
        &.select2-results__option--highlighted {
        }
      }
    }
  }
}
```

### Actual Behavior

![captura de tela 2017-12-23 as 16 09 22](https://user-images.githubusercontent.com/77889/34322043-b0cf72f4-e7fb-11e7-8b6a-dd80d023ba42.png)

![captura de tela 2017-12-23 as 16 09 26](https://user-images.githubusercontent.com/77889/34322044-b47aa7de-e7fb-11e7-90dd-98f9ec496182.png)

**Comment by KerryJones** [comment]
Any luck with more complicated selects? With icons and such?

**Comment by thadeu** [comment]
@KerryJones I think in order to the behavior initial expected to select an item, should be is this

**Comment by nicbet** [comment]
> Any luck with more complicated selects? With icons and such?

@KerryJones this worked for me:

### bulma-select2.scss
```scss
// Bulma
.select2-container {
  .select2-selection--single {
    height: auto !important;
    padding: 3px 0 !important;
    border: 1px solid #dbdbdb !important;

    .select2-selection__arrow{
      top: 5px !important;
    }

    .select2-selection__placeholder {
      color: #dbdbdb !important;
    }
    
    .select2-selection__rendered {
      margin-left: 2em;
    }
  }

  .select2-dropdown {
    border: 1px solid #dbdbdb !important;
    border-top: 0 !important;

    .select2-search {
      margin: 5px;

      .select2-search__field {
        padding: 10px !important;
        border-radius: 3px !important;
        font-size: 1rem;
        height: 2.25em;
        box-shadow: inset 0 1px 2px rgba(10,10,10,.1);
        max-width: 100%;
        width: 100%;
        border-radius: 3px !important;
      }
    }
    
    .select2-results__options {
      max-height: 200px !important;

      .select2-results__option {
        padding: 0.37em 0.75em !important;
        font-size: 1rem;
        
        &.select2-results__option--highlighted {
        }
      }
    }
  }
}
```

### form.html.erb
```erb
<div class="field">
  <label class="label">Which project?</label>
  <div class="control has-icons-left">
    <%= collection_select(:project, :project_id, Project.all, :id, :name, {prompt: true}, required: true) %>  
    <span class="icon is-small is-left">
      <i class="far fa-folder"></i>
    </span>
  </div>
</div>
```
