### ISSUE TITLE
Button that behaves / looks like link

### ISSUE THREAD

**Issue by tony** [jgthms/bulma#1583]
Similar bootstrap behavior of ``.btn-link``. Example:

<img width="977" alt="screen shot 2018-01-01 at 2 01 30 pm" src="https://user-images.githubusercontent.com/26336/34470678-649a31b4-eefc-11e7-95ff-4b97ed33345b.png">

Docs: https://getbootstrap.com/docs/4.0/components/buttons/

Source: https://github.com/twbs/bootstrap/blob/1a4a94bfd90626bdd48cea0c0d4bf0293f052edb/scss/_buttons.scss

This is helpful in cases of "back" buttons in form wizards, where forms need to be submitted when traversing form steps.

**Comment by aaronang** [comment]
@tony Is this what you are looking for? 
```html
<a class="button is-link">Link</a>
```
See https://bulma.io/documentation/elements/button/#colors for more information.

**Comment by tony** [comment]
``is-text`` and ``is-link`` aren't equivalent to bootstrap's ``btn-link``. They don't behave like a text link.

Bulma's ``is-link`` is only a color modifier. It's still a button.

Bulma's ``is-text`` has an underline, and the color / behavior isn't the same as a link. It has a background.

Bootstrap's ``.btn-link`` has no button styling. It looks like a normal link.

An example use case for this is when a backend requires a form submission (such as a session-based form wizard), but you want the back object to only show as a text link (not a button).

The only other way around that would be to use a link and begin wiring in JavaScript to simulate a form submission when a link is clicked.

**Comment by jimblue** [comment]
I agree with @tony, `button is-link` shouldn't be a color modifier but a look modifier to mimic a link.
An other good exemple is from Spectre: https://picturepan2.github.io/spectre/elements.html#buttons

<img width="802" alt="screen shot 2018-01-03 at 09 17 29" src="https://user-images.githubusercontent.com/10623367/34513151-f6e28c18-f066-11e7-96b3-c44db4b2a775.png">

Very useful feature!

**Comment by lpolon** [comment]
I've been using button tag with link styling in bulma with the following modifiers:

`<button class="button is-link is-light has-background-white">link</button>`

**Comment by jrock17** [comment]
This would be very useful. Any progress?

**Comment by devonlambert** [comment]
Any Progress on this one?

**Comment by svdHero** [comment]
I would also appreciate such a feature. I quite often have a Fontawesome icon that should trigger some action on mouse-click and that I want to style like a hyperlink, i.e. hyperlink color, mouse cursor, mouse-over effect, without having a button look-and-feel.

Maybe as a side-question: Is there already a button style that just renders a Fontawesome icon and nothing else? No, button border, no button background?

**Comment by getup8** [comment]
I'm using something like this, if helpful to anyone.  Could def be improved, I'm sure.

```scss
// A button that looks like a link. Useful for JS-only actions.
.button-link {
  font-weight: 400;
  color: $link;
  background-color: transparent;
  border-color: transparent;

  &:hover {
    color: $link-hover;
    text-decoration: underline;
    background-color: transparent;
    border-color: transparent;
  }

  &:focus {
    text-decoration: underline;
    border-color: transparent;
    box-shadow: none;
  }

  // Remove all padding and height so it's just plain, unpadded text.
  &.button-text {
    padding: 0;
    height: unset;
  }
}
```
