### ISSUE TITLE
New media breakpoint

### ISSUE THREAD

**Issue by bcarneiro** [jgthms/bulma#1677]
This is about **Bulma | the Docs**.
Is it a feature

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I think we need a new breaking step that should be something in the order of 480px.
this is just to differentiate the position in the mobile version between landscape and portrait.

Maybe call it $portrait or $landscape

**Comment by sandrina-p** [comment]
I agree, it's missing a smaller breakpoint at Bulma's framework, I called it `phone`:

```scss
@mixin phone {
  @media screen and (max-width: 479px) {
    @content;
  }
}

// ...

@include phone {
  .container { padding: 0 }
}
```

**Comment by alanaasmaa** [comment]
Also missing something between mobile and tablet. 
Trying to find and option to add all features to new breakpoints.
For eaxmple `is-4-phone`

**Comment by jasoncostello** [comment]
I just used Bulma on a project and really liked it. This was the only issue that stuck out to me. I will be adding this breakpoint to my own library for the future but it feels like it should be in the framework.

**Comment by poVoq** [comment]
Would be great if a breakpoint for smart feature phones (KaiOS) and embedded devices was added.

KaiOS devices usually come with 240 x 320 px screens (portrait or less common landscape) and key-pad input only.

**Comment by dunham-mike** [comment]
I recently completed a project using Bulma and agree that being able to differentiate between portrait and landscape widths on mobile would be quite valuable. I started playing with what adding these breakpoints to Bulma would look like, and it seems like not breaking existing mobile classes is key.

Here is what part of the docs would look like with "portrait" running from 0-480px, "landscape" running from 481-768px, and "mobile" running from 0-768px. This change would break the mutual exclusivity of the existing breakpoints for the first time:

![split docs](https://user-images.githubusercontent.com/59804733/82943332-4a3d0580-9f4e-11ea-801d-b34fdbe853e4.png)

This level of complication still seems worth it for the core framework, yes? Perhaps we add the portrait and landscape functionality to Bulma itself but don't add new columns to the docs and instead explain it with a text note. ([Here](https://bulma.io/documentation/modifiers/responsive-helpers/) is the existing docs page.)

I'd love some feedback before following through with the rest of these changes and submitting a pull request that would include changes to the docs.

**Comment by fabiofdsantos** [comment]
@m99coder opened a related PR: https://github.com/jgthms/bulma/pull/3058

**Comment by daniellenzofficial** [comment]
Hi guys, will this be merged?

**Comment by Zauberfisch** [comment]
@fabiofdsantos thanks for creating a PR. Though, as far as I can see you only added classes for .column, right?
In order for the maintainer(s) to merge this, I'm pretty sure they'll want support for is-flex and others too.

I'd also be willing to put in effort to push this forward, but first I agree, it would be nice to get some maintainer input if this would even get merged.

**Comment by Zauberfisch** [comment]
as a workaround meanwhile I am now using styles from @alanaasmaa with one addition:
```scss

$alignments: ('centered': 'center', 'justified': 'justify', 'left': 'left', 'right': 'right');

@each $alignment, $text-align in $alignments {
	@include mobile-xs {
		.has-text-#{$alignment}-mobile-xs {
			text-align: #{$text-align} !important;
		}
	}
	@include mobile-md {
		.has-text-#{$alignment}-mobile-md {
			text-align: #{$text-align} !important;
		}
	}
	@include mobile-lg {
		.has-text-#{$alignment}-mobile-lg {
			text-align: #{$text-align} !important;
		}
	}
}

```
