### ISSUE TITLE
replace overflow-y scroll to auto

### ISSUE THREAD

**Issue by TheColorRed** [jgthms/bulma#1689]
Maybe just my opinion, but I think that instead of 

```css
html {
  overflow-y: scroll;
}
```

It should be 

```css
html {
  overflow-y: auto;
}
```

With `scroll`, it forces a scrollbar to display if the page isn't long enough. Using `auto` will add the scrollbar only if needed, which looks cleaner.

https://github.com/jgthms/bulma/blob/master/sass/base/generic.sass#L28
