### ISSUE TITLE
SASS FEATURE REQUEST : Possibility to load components variables standalone

### ISSUE THREAD

**Issue by darkylmnx** [jgthms/bulma#1811]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.7.0** 

### Description

Today bulma gives the possibility to customize it with sass variables in **utilities**, BUT, it's impossible to use existing variables in components (navbar... with webpack sass-loader & vue-loader) because it means also loading the css classes which may have already been loaded elsewhere.

This is mostly because webpack with sass-loader doesn't share variables accross **.vue** files BUT, if **component variables** where loadable independently it would fix this issue as many people using bulma use webpack and Vue too.

### Steps to Reproduce
- Create a simple projet with Vue-cli
- Load bulma in main.js or in an index.scss that you load in main.js
- Try to use **$navbar-dropdown-z** in a component

### Expected behavior
I expect the variable to be usable.

### Actual behavior
You'll see that this throws an error saying "undefined variable", that's because of how sass-loader and vue-loader handles it and there not going to change that anytime I think.

BUT, if each component had it's own variables file like : 
`bulma\sass\components\navbar-vars.sass` 
which would be loaded in :
`bulma\sass\components\navbar.sass`
It would make those variables easily re-usable (for each component btw).

Today i had to tweek this and copy each variable from bulma to my own scss files which is not really maintainable if i upgrade my bulma version.

What do you think ? Any othr suggestion ?

**Comment by Come2Daddy** [comment]
For maintainability, each vars should be stored in the same file, and be namespaced to avoid collision.

**Comment by darkylmnx** [comment]
@Come2Daddy I agree but that's not the discussion here. The problem here is that bulma components bars are seperate from utility vars which makes it difficult to customize because in those files you also have the css and not only the vars.

**Comment by darkylmnx** [comment]
@Come2Daddy and what youre saying is not possible in frameworks with webpack loaders like Vue loader which loads each scss files for each .vue file.
Anyway I don't see why component variables and the component css are in the same file. The goal of sass and pre processors is to compose things as much as possible and make a separate file for vars woun't Jill anyone

**Comment by Come2Daddy** [comment]
I'm not into webpack nor vue. Just telling what i'm thinking about the current state of bulma and your request. Meaning I presonnaly am against this structure, as I'm already concerned by seeing vars definition in components/elements sources. For now, I can't figure out your issue, and as far as it is webpack/vue related I won't dive deeper than this.

**Comment by darkylmnx** [comment]
This is not webpack related this is related to bundlers in general.

If I need default variables from navbar for example, I have to import the navbar in my scss file. Example :
In my index.scss let's say I have this
```scss
@import 'my-custim-vars-of-bulma';
@import '~bulma';
```

Now let's say somewhere else in my custom scss files, I need to use a default var from bulm
```scss
@import '~bulma/components/navbar.scss';

.sep {
height: $navbar-height;
}
```

Well no here I have css duplication. Even in a simple project with gulp this is an issue. Because bundlers execute each scss files independently so I lost the scope

**Comment by Come2Daddy** [comment]
I don't doubt about this...

**Comment by darkylmnx** [comment]
@Come2Daddy did you see the issue though ? On one side you pute all bulmas utility variables separately and on the other side you don't want component variables to be separate, isn't that confusing ? Especially when what people need to customize to not enter a all-bootstrap-look-alike problem is components ?

Anyway, I woun't push it as maybe I should wait for more people to fill my issue but, just to let you know : 
https://github.com/search?utf8=%E2%9C%93&q=bulma+vue&type=
![image](https://user-images.githubusercontent.com/1426357/39321931-9b2b4204-4988-11e8-9e40-df9ebb086aae.png)

546 repos have vue and bulma usd in it
2000 repos have vue in it
Conclusion : 1/4 of bulma respos use Vue. Just think about that.

**Comment by Come2Daddy** [comment]
I repeat myself, I don't doubt bulma is mostly used along with SPA frameworks.

You whish to have a file containing vars per component/element, I propose something similar, but more general with only one file with all vars. What's wrong with this in your case ?

I would like to have vars in a var file, mixins in a mixin file and functions in a function file... as we have navbar in its own file... maintainability & flexibility.

**Comment by darkylmnx** [comment]
I'm not against every vars in one file.

Le sam. 28 avr. 2018 à 17:13, ludovic landier <notifications@github.com> a
écrit :

**Comment by jgthms** [comment]
Solution is to set your own $my-custom-z and set $navbar-dropdown-z to that variable.

**Comment by darkylmnx** [comment]
@jgthms I think you misundestood, I don't need to customize $navbar-dropdown-z, I need to use it somewhere in my code for a custom css based on it's current value, but when I import navbar.css it also imports the associated css (which is not wanted and causes duplication as I already loaded bulma.sass somewhere else)

**Comment by darkylmnx** [comment]
@jgthms what It's an issue caused by the bundler (webpack) but it demonstrate a flaw in bulma's current architecture IMO that is : why do component variables are located elswhere from utility variables ? Why do one file mixe css declarions + sass variables ? That's the main flaw I'd like you to checkout and discuss if you find it work it and interesting.

**Comment by jgthms** [comment]
It's because Bulma is modular. It wouldn't make sense to define `$navbar-dropdown-z` if it's not used at all.

Hence my solution to create a new variable in the "upper" scope.

**Comment by darkylmnx** [comment]
@jgthms since it's modular, it would make to sens to have something like 
```scss
// in navabar.scss file
@import './navbar-vars';
@import './navbar-css';

// in navbar-vars.scss
$navbar-height... // and all other navbar vars

// in navbar-css.scss
.navbar {
  height: $navbar-height
}
```

IMHO this is way more module because, if I need, for some reason (which is my case) to use the navbar(s variables, let's sya to enhance the navbar with new markup elements such as a separator ou anything, and that I need some values of the actual navbar (not new values, current values used by the navbar), I can then import only the vars I need and not duplicate the whole css again.

To make this clear this is how my current app looks like : 

```javascript
// in main.js of my vue app (but this could be any webpack based web app)
import './index.scss'
import Vue from 'vue'
... // bunch of stuff for my app to run
```
```scss
// in index.scss
@import './bulma-custom';
@import '~animate.css';
@import '~bulma';

body { ... } // and all my global CSS overrides

/* HERE WEBPACK WILL INJECT MY SCSS FILES LOADED FROM MY VUE FILES */
/* BUT : webpack will scope each of my scss files, so they woun't be aware of variables declared in the global files above */

// in bulma-custom.scss
// 1. Import the initial variables
@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/functions";

// 2. Set your own initial variables
// Update blue
$blue: #72d0eb;
... 
/* 
every customisation done according to your docs : 
https://bulma.io/documentation/overview/customize
*/
```

```vue
// in my header.vue file
<template>
    <nav class="navbar"> ... </nav>
</template>

<script> export default {} </script>

<style lang="scss">
// because webpack handles this
// he scopes this file so I don't have accès to anything here
// I have to import manually
@import './bulma-custom';
// now I have access to my custom vars + utility vars but not to any of bulma's component vars
// here's the problem, if i import it my self
@import '~bulma/sass/components/navbar'
// this navbar.sass indeed has the variables but also the css, so I now have imported the navbar's css 2 times
// one with @import '~bulma' above, and one here
// I need the navbar's default height, not to set a custom one
.custom-sep {
   height: #{($navbar-height - pxToRem($sep-margin * 2))};
}
</style>
```

I hope this breaks down the use case
