### ISSUE TITLE
Universal SVG Icon Support

### ISSUE THREAD

**Issue by nedpals** [jgthms/bulma#1867]
This is about **Bulma**.

Is it about Bulma or about the Docs? **Bulma**
Is it a bug/feature/question or do you need help? **Enhancement of a feature**
If it's a bug, is it a browser bug? **Nope.**

### Overview of the problem
This is about the Bulma **CSS framework**
I am sure this issue is **not a duplicate**

### Description
I am using a specific SVG icon stack ([feathericons/feather](https://github.com/feathericons/feather)) and having a workaround for margin is fine for me. But the problem is that they don't scale in let's say in this example the input fields wherein if I set the field `is-large` the SVG icon does not scale. The question is, will there be an official support for all SVG icons aside from Font Awesome 5? 

### Expected behavior
![image](https://user-images.githubusercontent.com/7358345/39966352-1a249d60-56dd-11e8-8296-80c1cef7b0ff.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/7358345/39966315-633abaf8-56dc-11e8-9519-a40afd4134bd.png)

**Comment by AdsonCicilioti** [comment]
Hello gegg!
Feather Icons are beautiful, I use and recommend. So I recommend using SVG icons. I'm new here and I have not yet seen how Bulma handles icons from another library, but I'll try to help.

Here I use the following CSS markup for `<svg>` containing the class `icon`:

``` css
[class*=" icon"], [class^=icon] {
    display: inline-block;
    width: 1em;
    height: 1em;
    stroke-width: 0;
    stroke: currentColor;
    fill: currentColor;
    line-height: 1;
    position: relative;
    top: -.05em;
    vertical-align: middle;
}
```
In this way the icon will have its size defined by the `font-size` inherited by the parent element, being able to be in a button, an input form, or simply in line in any text. And if you need it to be anywhere else in a devious way and need to set a size to the svg icon directly just use `font-size '.

Remember that feather-icons are based on strokes and you might have to set `fill` to` none`;

Good job. I hope it helps!
