### ISSUE TITLE
gray out text color in disabled container

### ISSUE THREAD

**Issue by jinjor** [jgthms/bulma#1892]
This is about **Bulma**.
This is not a bug, a kind of question.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.1
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Description

I want to make all children in container grayed-out. But it looks Bulma has no feature to achieve it. Am I missing something?

I have a dropdown menu and each item in its menu should not be clicked when it is currently selected. Each menu item can have arbitrary content. So I can put colored icons in it.  

```html
<div class="dropdown is-active">
  <div class="dropdown-menu " id="dropdown-menu3" role="menu">
    <div class="dropdown-content">
      <li class="dropdown-item dropdown-item-disabled"> <!-- disabled item -->
        <span class="has-text-success">
          Foo
        </span>
      </li>
      <li class="dropdown-item">
        <span class="has-text-danger">
          Bar
        </span>
      </li>
    </div>
  </div>
</div>
```

The problem here is `has-text-*` is marked as `!important`. So I cannot make them grayed-out by modifying the container.

In this specific case, adding a feature to disable menu item would be also great.

### Steps to Reproduce

Write the above.

### Expected behavior

![image](https://user-images.githubusercontent.com/2568148/40520160-32750500-5fff-11e8-8bf5-e273490a2713.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/2568148/40520149-20be558c-5fff-11e8-9f13-577dee841967.png)

### Workaround

In my project, I finally added the following style.

```css
.dropdown-item.dropdown-item-disabled,
.dropdown-item.dropdown-item-disabled:hover {
  color: $text;
  cursor: default;
  background-color: initial;
  filter: grayscale(1);
  opacity: 0.5;
} 
```
