### ISSUE TITLE
Vertically top aligning for menu?

### ISSUE THREAD

**Issue by rhea-s** [jgthms/bulma#1916]
This is about **Bulma**.

### Overview & Description of the problem

I'm new to Bulma and trying to create a menu sidebar and have it aligned in the top left corner.

### Steps to Reproduce

This fiddle reproduces the issue: https://jsfiddle.net/to2uyqn9/1/ 

### Expected behavior

I would like the menu to be aligned in the top left but as you can see, it's vertically centered. If this is due to using the hero banner as the background, is there any other way to achieve the same is-dark is-bold background? If it is due to something else, how can I fix it?

**Comment by emkajeej** [comment]
The `.hero` component automatically centers all content vertically. I agree that a modifier would be preferred here.
However for now you can override it by changing
```css
.hero.is-fullheight .hero-body {
  align-items: center;
}
```
to
```css
.hero.is-fullheight .hero-body {
  align-items: flex-start;
}
```

I would personally override it by adding an extra class to your `.hero` lest you change the default behaviour of all `.hero` components.
