### ISSUE TITLE
Loading border-color is the same when colorize with .button.is-outlined:focus state.

### ISSUE THREAD

**Issue by nakorndev** [jgthms/bulma#1979]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1]

### Description

Sorry for my English.

After I submit form the `.is-loading` will append to `.button.is-outlined`. The spinner will show the same color as button. This code is fixed for me but I don't know how to contribute also, I'm not good with sass. Please someone pull request for next version.

```css
.button.is-outlined:focus.is-loading::after {
  border-color: transparent transparent $white $white !important;
}
```

### Steps to Reproduce

Can I send as GIF link? I think it's easy to see the problem: https://gfycat.com/ScaredForkedCollardlizard

### Expected behavior

Show the white color when the button is on `:focus` state

### Actual behavior

Show the same color of `background-color`. Then they is no spinner shown.
