### ISSUE TITLE
Wrong CSS output using $custom-shades

### ISSUE THREAD

**Issue by hal0gen** [jgthms/bulma#2031]
This is about **Bulma**.

### Overview of the problem
I cannot add a custom shade and have it processed by the framework.

### Description

Using Bulma 0.7.1. I am trying to define custom shades and add a color to it (i.e. _fuchsia_). I need to find a way for having the corresponding helper classes generated (`.has-text-fuchsia .has-background-fuchsia`). 

### Steps to Reproduce
From my understanding of the customization, I should add `$fuchsia` to `$custom-shades`, and not to `$custom-colors` (which are used for semantic purposes). 

````scss
$fuchsia: #d705a3
$custom-shades: ("fuchsia": $fuchsia);
````

When I do that, Bulma first runs `mergeColorMaps` and then generates the classes, except the ones corresponding to `$custom-shades` are wrong, because `findColorInvert` is also called, which adds `#fff` as the default inverted color. This works without problems if I use `$custom-colors` (either specifying the inverted color or not). 

### Expected behavior
The CSS output should be:

````css
.has-text-fuchsia {
    color: #d705a3 !important;
} 
````

### Actual behavior
The CSS output is:

````css
.has-text-fuchsia {
    color: #d705a3, #fff !important;
} 
````
