### ISSUE TITLE
Mini-reset conflicting with safari

### ISSUE THREAD

**Issue by Mark-Hoog** [jgthms/bulma#2033]
This is about **Bulma**.

### Overview of the problem
Transitioning of a pseudo element with svg content inside.

I'm using Bulma **version** [0.7.1] 
My **browser** is:
Safari 11.1.2

### Description
When transitioning a pseudo (after) element on hover safari doesn't render the transitioning or sometimes doesn't render anything at all. 

### Steps to Reproduce
1. First Step
Visit: https://codepen.io/anon/pen/VBXWmR

2. Second Step
Change the following in the css 
``` css
*, * > ::after, * > ::before {
  box-sizing: inherit;
}
```

to 

```css
*, * > ::after, * > ::before {
  box-sizing: border-box;
}
```

### Expected behavior
Transitioning of the element

### Actual behavior
Safari doesn't render the transitioning 

I'm aware that this is as much a safari issue as a css issue. Or perhaps I am overlooking something.
