### ISSUE TITLE
Dropdown chevron without font-awesome

### ISSUE THREAD

**Issue by Heliosmaster** [jgthms/bulma#2118]
This is about **Bulma**.

### Overview of the problem

 This is about the Bulma **CSS framework**

 I'm using Bulma **version** [0.7.1]
 I am sure this issue is **not a duplicate**

### Description
Right now the `select` element has a (default blue) chevron made purely with CSS. The `dropdown`, instead, uses font-awesome for the chevron/arrow.

It would be good to add the capability of adding a pure CSS implementation of the arrow also for the dropdown element.

**Comment by Heliosmaster** [comment]
Ps, seeing as [here](https://github.com/jgthms/bulma/blob/master/sass/components/dropdown.sass) there is a `$dropdown-content-arrow: $link !default` that is not used, it might be related?

**Comment by janydrozd** [comment]
@jgthms is it still open? I could work on this.

**Comment by bodograumann** [comment]
I would suggest this, akin to the `.select` solution:

```scss
.dropdown-trigger > button {
  min-width: 12rem;

  &::after {
    @extend %arrow;
    border-color: $input-arrow;
    right: 1.125em;
    z-index: 4;
  }
}
```
