### ISSUE TITLE
Sass generates wrong output for layout/hero.sass

### ISSUE THREAD

**Issue by thijsw** [jgthms/bulma#213]
### Checklist

* [ ] I'm using Bulma **version** [0.0.26]
* [ ] This is a **Sass** issue: I'm using version [x.x.x]

### Description

I am importing the library in my own project, via `@import` statements in a Laravel project. Laravel has its own wrapper around the compiling-tools, called Elixir. The generated css contains a bug in the `.hero` layout file.

This snippet ...
```sass
      // sass/layout/hero.sass, line 84 onwards
      a.nav-item,
      .nav-item a:not(.button)
        color: rgba($color-invert, 0.5)
        &:hover,
        &.is-active
          color: $color-invert
```
... yields unexpected output: (multiple times, because it is in a loop, for example: with `.is-info`)
```css
    .hero.is-info a.nav-item,
    .hero.is-info .nav-item a:not(.button):not(.pagination a) {
      color: rgba(255, 255, 255, 0.5); }
      .hero.is-info a.nav-item:hover, .hero.is-info a.nav-item.is-active,
      .hero.is-info .nav-item a:not(.button):not(.pagination a):hover,
      .hero.is-info .nav-item a:not(.button):not(.pagination a).is-active {
        color: white; }
```

The addition `:not(.pagination a)` gets incorrectly appended.
If I change the `.button` class to a made-up class `.buttonxxx`, the error disappears:

```css
    .hero.is-primary a.nav-item,
    .hero.is-primary .nav-item a:not(.buttonxxx) {
      color: rgba(255, 255, 255, 0.5); }
      .hero.is-primary a.nav-item:hover, .hero.is-primary a.nav-item.is-active,
      .hero.is-primary .nav-item a:not(.buttonxxx):hover,
      .hero.is-primary .nav-item a:not(.buttonxxx).is-active {
        color: white; }
```

### Steps to Reproduce

1. Import library in a project
2. Run compiler
3. See generated css file
