### ISSUE TITLE
text-decoration none on tab links

### ISSUE THREAD

**Issue by piuccio** [jgthms/bulma#2131]
This is about **Bulma**.

### Overview of the problem

I'm using Bulma **version** [0.7.1]

I am sure this issue is **not a duplicate**?

### Description

The global style for bulma includes

```css
a {
  text-decoration: none;
}
```

which is arguable, but that's not the problem.

I'm also using ant.design which includes the following

```css
a:focus {
  text-decoration: underline;
}
```

So when I use tabs like in the documentation

```html
<div class="tabs">
  <ul>
    <li><a>Pictures</a></li>
    <li><a>Music</a></li>
  </ul>
</div>
```

I end up with tab links that are underlined when I click on them.

### Steps to Reproduce

Just add the following in your global css

```css
a:focus {
  text-decoration: underline;
}
```

and use a tabs component

### Expected behavior

Links without underline

### Actual behavior

Wouldn't it be better if `tabs` didn't rely on the global styles from `a` but redefined the fact that `.tabs a` should not be underlined under any condition?

I could probably submit a PR if you guys are interested
