### ISSUE TITLE
[Question] Insert button in tabs

### ISSUE THREAD

**Issue by matsumurae** [jgthms/bulma#222]
### Checklist

* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [x] I'm using Bulma **version** [0.0.26]
* [x] My **browser** is: Chrome (Mac)
* [ ] This is a **Sass** issue: I'm using version [3.4.21]
* [x] I am sure this issue is **not a duplicate**?

### Description

I want to add any component inside the tabs div, like buttons or labels. I don't know the right manner to do this. Thinking in the syntax of bulma, it should be done using an unordered list and inserting inside the component.  

So, this are my *fixes*:
- Using an unordered list as container for the button can take advantage of the `tabs` classes and position wherever I want. **But** adds a border bottom when hover, due to element selector in sass instead of class.
- Using columns for contain the tabs and the desired component. I'll explain above.

#### Fix 1
1. Create a div with the `tabs` class.
2. Inside it, create two unordered lists.The first should have `is-left` class and second, `is-center`.
3. Inside the `is-left` list, insert simple tabs like `<li><a class="is-tab">Tab 1</a></li>`.
4. Inside the `is-right` list, insert an anchor with `button` class.

HTML:
```html
<div class="tabs is-centered is-medium">
    <ul class="is-left m-0">
       <li class="is-active">
         <a class="is-tab">Tab 1</a>
       </li>
       <li>
         <a class="is-tab">Tab 2</a>
       </li>
       <li>
         <a class="is-tab">Tab 3</a>
       </li>
    </ul>
    <ul class="is-center">
       <a href="#" class="button is-medium is-primary">filters</a>
    </ul>
</div>
```

```css
// sass dynamically generated classes with each loop
// but inserted here for testing
.m-0 { margin: 0; }

// Remove hover style to not affect buttons
.tabs a {
  &:hover {
    border-bottom: none;
    color: inherit;
  }
}

// Tabs hover and style - using .tab class
.tabs a.is-tab {
  margin-bottom: 0;
  border-bottom: none;

  &:hover {
    border-bottom: 1px solid #363636;
    color: #363636;
  }
}
```
_Expected behavior:_ Have a normal behavior on hover when a button is inside a tabs container.

_Actual behavior:_ Imitates the tabs hover adding a border bottom to button when hover.

_Fix behavior:_ As desired.

#### Fix 2
1. Create a div with `nav-filter columns` class.
2. Create inside a nav with `column tabs is-centered is-medium m-0 p-0` class and a div with `column is-narrow p-0` class.
3. Create inside the nav an unordered list. Inside, add the list as above.
4. Create inside the div a new div with `filter-item` class. Inside this, add the anchor as above.

HTML:
```html
<div class="nav-filter columns">
    <nav class="column tabs is-centered is-medium m-0 p-0">
      <ul>
        <li class="is-active"><a>Tab 1</a></li>
        <li><a>Tab 2</a></li>
        <li><a>Tab 3</a></li>
      </ul>
    </nav>
    <div class="column is-narrow p-0">
      <div class="filter-item">
        <a href="#" class="button is-uppercase is-medium is-accent-light">filters</a>
      </div>
    </div>
</div>
```

CSS:
```css
// sass dynamically generated classes with each loop
// but inserted here for testing
.p-0 { padding: 0; }
.m-0 { margin: 0; }

// Remove bottom border from tabs
.tabs ul { border-bottom: none; }

// Nav container
.nav-filter { border-bottom: 1px solid #d3d6db; }
.nav-filter.columns { margin-top: 0; } // Remove margin for contain components inside the column

// Nav items (anything that is not a tab)
.filter-item { padding: 8px 20px; }
```

### Solutions
This is not explained in the docs, like #217 about full-width button in hero.

#### Fix 1
Changing sass: instead of `.tabs a:hover` use a class selector as the above example `.tabs .is-tab`. With this, the problem is solved and everyone can benefit of this.

This *should* be the fix.

#### Fix 2
This is a weird fix, because adds a lot of html for add a simple button next to tabs. But, fixes the problem.
