### ISSUE TITLE
feature request: provide CSS option to change nav breakpoint

### ISSUE THREAD

**Issue by Hongbo-Miao** [jgthms/bulma#2259]
This is about **Bulma | feature**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.72

### Description

Originally asked on [Stack Overflow](https://stackoverflow.com/questions/53406041/how-to-change-the-nav-breakpoint-by-css-only-in-bulma).

I am using Bulma. Right now the navbar collapse and change to a burger menu when the width is less than 1088px on my browser. I hope to make it collapse only when less than around 768px or even smaller.

For the nav
```html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>
    </div>
  </div>
</nav>
```

I cannot find an easy way to overwrite nav breakpoint using CSS only.
It would be great to provide a way, for example, additional class name to customize the breakpoint. 

Something like
```html
<nav class="navbar">
<nav class="navbar is-mobile">
<nav class="navbar is-tablet">
<nav class="navbar is-desktop">
```
to allow different break point to become burger menu.

By the way, thanks for the awesoooom framework!

**Comment by arvind0598** [comment]
I've had the same issue. Something like ```<nav class="navbar break-when-mobile">``` or ```<nav class="navbar break-when-tablet">``` would be a great idea.

**Comment by mobayen** [comment]
the breakpoint variable to customize already is available:
`$navbar-breakpoint: 769px;`

**Comment by Hongbo-Miao** [comment]
Hi @mobayen, thanks, however, I am looking for a CSS solution (not SCSS)

**Comment by Greenscreener** [comment]
Gist of the workaround: https://gist.github.com/Greenscreener/0fa6a2bc8534eab615841740cf2acd90
It's definitely not perfect, change as you like. Again, I copied it from Bulma's soource, so it can be a bit weird.

**Comment by Hongbo-Miao** [comment]
Acticate

**Comment by Romej** [comment]
I just came across the same problem.

I ended up using the following CSS rules :

@media screen and (min-width: 768px) and (max-width: 1024px) {
    .navbar>.container {
        align-items: stretch;
        display: flex;
        min-height: 3.25rem;
        width: 100%;
    }
    .navbar-burger {
        display: none;
    }
    .navbar-menu {
        background-color: transparent;
        box-shadow: 0 0 0 0;
        padding: 0;
        align-items: center;
        justify-content: flex-end;
        flex-grow: 1;
        flex-shrink: 0;
    }
    .navbar, .navbar-end, .navbar-menu, .navbar-start {
        display: flex;
        align-items: stretch;
    }
    .navbar-item {
        display: flex;
        align-items: center;
    }
}

**Comment by amimas** [comment]
Thanks for the workaround snippet @Romej . I tried it and realized that it doesn't handle dropdowns in the menu. Updated it slightly by adding adding `navbar-dropdowns` in your snippet and it worked pretty well.

```css
@media screen and (min-width: 768px) and (max-width: 1024px) {
    .navbar>.container {
        align-items: stretch;
        display: flex;
        min-height: 3.25rem;
        width: 100%;
    }
    .navbar-burger, .navbar-dropdown {
        display: none;
    }
    .navbar-menu {
        background-color: transparent;
        box-shadow: none;
        padding: 0;
        justify-content: flex-end;
        flex-grow: 1;
        flex-shrink: 0;
    }
    .navbar, .navbar-end, .navbar-menu, .navbar-start {
        display: flex;
        align-items: stretch;
    }
    .navbar-item {
        display: flex;
        align-items: center;
    }
}
```

There's still one issue I noticed when debugging in my desktop view. If I manually changed the window size to below 768px and then click on the hamburger icon to display the menu and then resize the window to be bigger than 768px again, the `navbar-menu` remains on the left side even though `navbar-end` is set on it. You'll have to get back to the mobile view and click on the hamburger icon to close the menu and then resize it again.
