### ISSUE TITLE
Support is-fullwidth table in box [feature request]

### ISSUE THREAD

**Issue by rewritten** [jgthms/bulma#2274]
This is about **Bulma**.

It is a **feature request**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.2]
I am sure this issue is **not a duplicate**

### Description

Full width tables in box elements could be much better if the width of the table would eat up the box padding. The idea is that the table has cell paddings, and the box has padding, so the cell paddings should blend into the box padding when appropriate.

This is the html code:

```html
<div class="box">
  <h1 class="title">Some Title</h1>
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>One</th>
        <th>Two</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Three</td>
        <td>Four</td>
      </tr>
      <tr>
        <td>Five</td>
        <td>Six</td>
      </tr>
      <tr>
        <td>Seven</td>
        <td>Eight</td>
      </tr>
      <tr>
        <td>Nine</td>
        <td>Ten</td>
      </tr>
      <tr>
        <td>Eleven</td>
        <td>Twelve</td>
      </tr>
    </tbody>
  </table>
</div>
``` 

Here is the current rendering:

![bulma-box-table-current](https://user-images.githubusercontent.com/476895/49685192-7e650200-fadf-11e8-96c4-2ed50000da27.png)

With the following changes (not tested with responsive etc, and just based on the inspector stylesheet):

```css
.box > .table.is-fullwidth {
    margin-left: -1.25rem;
    margin-right:  -1.25rem;
    width: calc(100% + 2.5rem);
}

.box > .table.is-fullwidth:last-child {
    margin-bottom: -1.25rem;
}

.box > .table.is-fullwidth td:first-child,
.box > .table.is-fullwidth th:first-child {
    padding-left: 1.25rem;
}

.box > .table.is-fullwidth td:last-child,
.box > .table.is-fullwidth th:last-child {
    padding-right:  1.25rem;
}
```

this is the new rendering. 

![bulma-box-table-proposal](https://user-images.githubusercontent.com/476895/49685195-8a50c400-fadf-11e8-9855-96f82dafdcfe.png)
