### ISSUE TITLE
Styles hard to override due to selectors used

### ISSUE THREAD

**Issue by WouterFlorijn** [jgthms/bulma#2292]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.2]
I am sure this issue is **not a duplicate**?

### Description

Title styles are unnecessarily nested, making them hard to override. This applies to many other Bulma styles as well.

This is more of a discussion point, as I know this probably isn't going to be fixed soon. I think Bulma uses very unidiomatic CSS in quite a few cases, making styles very rigid and hard to override. At the moment this is a dealbreaker for me and forces me to switch to another framework.

I think this is particularly strange for Bulma, because in other cases it's very flexible. For example it doesn't apply basic styles unless you tell it to (which I like).

### Steps to Reproduce

CSS:
```css
.margin-bottom {
    margin-bottom: 32px;
}
```

HTML:
```html
<h1 class="title is-1 margin-bottom">Test</h1>
```

### Expected behavior

`margin-bottom: 32px;` is applied.

### Actual behavior

`margin-bottom: 32px;` is not applied, since the selector used by Bulma is higher prio:

```css
.box:not(:last-child), .content:not(:last-child), .notification:not(:last-child), .progress:not(:last-child), .table:not(:last-child), .table-container:not(:last-child), .title:not(:last-child), .subtitle:not(:last-child), .block:not(:last-child), .highlight:not(:last-child), .breadcrumb:not(:last-child), .level:not(:last-child), .list:not(:last-child), .message:not(:last-child), .tabs:not(:last-child) {
    margin-bottom: 1.5rem;
}
```
