### ISSUE TITLE
The actual gap (horizontal margins) of the fluid container is not 32px but 64px

### ISSUE THREAD

**Issue by DevelAx** [jgthms/bulma#2306]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs** 

### Description
The docs state that:
> This container is fluid: it will have a **32px gap** on either side, on any viewport size.

But the actual gap is 64px on both sides even in the example where the quoted text [is placed](https://bulma.io/documentation/layout/container/).  

### Expected behavior
The fluid container gaps should be 32px each.

### Actual behavior
The fluid container gaps are 64px each.

--------------
The style copied from Chrome debug panel:
```css
@media screen and (min-width: 1088px)
.container.is-fluid {
    margin-left: 64px;
    margin-right: 64px;
    max-width: none;
    width: auto;
}
```
