### ISSUE TITLE
$navbar-breakpoint breaks nav style within certain breakpoints

### ISSUE THREAD

**Issue by mirukushake** [jgthms/bulma#2334]
This is about Bulma.

It is a bug.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.2]
My **browser** is: Chrome 71.0.3578.98

I am sure this issue is **not a duplicate**

### Description
I am using Bulma via Buefy/NUXT.

When using $navbar-breakpoint: $tablet in custom scss, the navbar loses style (is-info, is-link, etc.) and turns white between 769 and 1087px.

### Steps to Reproduce

```
@import "~bulma/sass/utilities/_all";

$navbar-breakpoint: $tablet;

@import "~bulma/bulma";
@import "~buefy/src/scss/buefy";
```

### Expected behavior

The navbar should stay the same color.

![screen shot 2019-01-26 at 6 17 37 pm](https://user-images.githubusercontent.com/12268816/51785180-3d13d900-2197-11e9-9566-834311b6b948.png)

### Actual behavior

![screen shot 2019-01-26 at 6 17 20 pm](https://user-images.githubusercontent.com/12268816/51785175-2a010900-2197-11e9-983e-72e67a02604d.png)

And on link hover:

![screen shot 2019-01-26 at 6 22 54 pm](https://user-images.githubusercontent.com/12268816/51785193-7d735700-2197-11e9-8466-64cec636626b.png)

Changing the $navbar-background-color variable does not change the behavior either.

**Comment by Dugnychon** [comment]
Issue still affecting recent Bulma versions. Could a new issue be created?

**Comment by ton2win** [comment]
I can confirm the issue.

**Comment by AjahnCharles** [comment]
**How do we get this re-opened?**

I'm seeing the same with Bulma 0.7.5 (via Buefy 0.8.18). I tried depending on Bulma directly to raise the version to 0.8.2 (I think I can, right?!?). Both show the bug. My navbar loses `is-primary`. It also appears to gain a little vertical padding:

Mobile:
<img width="499" alt="Navbar Mobile" src="https://user-images.githubusercontent.com/31621095/82352072-ac19de80-9a27-11ea-8b77-ffcac4c9aaef.png">

Tablet:
<img width="840" alt="Navbar Tablet" src="https://user-images.githubusercontent.com/31621095/82351626-02d2e880-9a27-11ea-88df-0003f14f65fa.png">

Desktop:
<img width="1078" alt="Navbar Desktop" src="https://user-images.githubusercontent.com/31621095/82352259-edaa8980-9a27-11ea-96f7-512a7baa60cd.png">

**Comment by elmatou** [comment]
I got it too, while setting `$navbar-breakpoint:` to a lower value to keep menu visible even on mobile, I noticed that it do not display very well because the menu background kick at 1023px and below `@media screen and (max-width: 1023px)` even if `$navbar-breakpoint` is set to a lower value.

this line should be updated by :
https://github.com/jgthms/bulma/blob/bd1b032be84ba7c6334199c3fa18e789fd04eead/sass/components/navbar.sass#L236
&
https://github.com/jgthms/bulma/blob/bd1b032be84ba7c6334199c3fa18e789fd04eead/sass/components/navbar.sass#L248

but strangely I keep getting `@media screen and (max-width:1023px) {` after sass compilation (though vue-cli / buefy)

my bulma version is 0.7.5

**Comment by elmatou** [comment]
it appears there is two set of rules in my compiled file :
around line 5032 :
```css
@media screen and (max-width: 499px) {
.navbar > .container {
    display: block;
}
...
.navbar-menu {
    background-color: #34495e;
    box-shadow: 0 8px 16px rgba(10, 10, 10, 0.1);
    padding: 0.5rem 0;
}
...
```
Which hold the correct behaviour ( `$navbar-breakpoint:500px` in this case)

and around line 9868
```css
@media screen and (max-width: 1023px) {
.navbar {
    color: #ecf0f1;
}
.navbar .navbar-menu {
    background-color: #ecf0f1;
    border-radius: 0 0 0.4em 0.4em;
}
...
```
Which hold the faulty rules

Clearly the sccss was loaded tow times with `$navbar-breakpoint` reset between them. Still investigeting, but there is some thing with the loading of bulma/buefy and bootswatch theme.
