### ISSUE TITLE
Style :invalid pseudo-class

### ISSUE THREAD

**Issue by gdude2002** [jgthms/bulma#2384]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I am sure this issue is **not a duplicate**

### Description

Would it make sense for Bulma to style input elements using the `:invalid` pseudo-class?

Say we have an `<input type="email">`. If we don't enter an email address into the field, most browsers will add the `:invalid` pseudo-class to the element and display a tooltip error, looking something like this:

![image](https://user-images.githubusercontent.com/204153/53570245-eca8e600-3b5d-11e9-9cfc-31c9142a2289.png)

If we end up clicking somewhere else on the page though, most browsers will dismiss that tooltip and we just get this:

![image](https://user-images.githubusercontent.com/204153/53570278-05b19700-3b5e-11e9-98bb-37c88e3b90a7.png)

I feel like it would make more sense if Bulma's SASS allowed this to match the `is-danger` class:

![image](https://user-images.githubusercontent.com/204153/53570347-2aa60a00-3b5e-11e9-92c7-49586ce40c2c.png)

---

Obviously, this is no replacement for server-side validation of your forms. That said, I feel like it would make for a nicer UX, and I feel like adding this probably wouldn't result in much extra SASS.

**Comment by suisoku** [comment]
I'm surprised that bulma doesn't have pseudo-class support

**Comment by gdude2002** [comment]
Me too, and I feel like it would probably be relatively easy to add as well - perhaps @jgthms is waiting for a PR instead?

I'd do it myself if I didn't have a ton of communities to run.

**Comment by brunokim** [comment]
Is there any workaround for this, even if using JS? So far I've only found calls to repeating Bulma styling in pseudoclass selectors.

**Comment by yamin-oanda** [comment]
@brunokim you can do something like:

```javascript
document.querySelectorAll('.input, .textarea, .select, input[type=checkbox], input[type=radio], .file-input').forEach(field => {
  field.addEventListener('invalid', () => {
    field.classList.add('is-danger');
    field.onchange = () => field.classList.remove('is-danger');
  })
});
```

**Comment by t1** [comment]
A full `is-danger` on a field looks too heavy to me for a validation error, so I just marked the border and put that into my own css file:

```css
.input:user-invalid {
    border-color: var(--bulma-danger);
}
```

Additionally, I've added an asterisk to the label of required fields:

```css
.field:has(:is(input, textarea, select):required) .label::after {
    content: " *";
    color: var(--bulma-danger);
}
```

What do you think?

**Comment by yamin-oanda** [comment]
I use the following:

```css
select.is-required, input.is-required, input.is-required + .file-cta {
  border-left-width: 4px;
}   
```

The left border being a bit thicker feels a bit more elegant than an asterisk symbol.
