### ISSUE TITLE
Bulma's core utility classes are hardcoded rather than referencing SCSS vars

### ISSUE THREAD

**Issue by ffxsam** [jgthms/bulma#2389]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.2
My **browser** is: Chrome 72

### Description

Bulma has documentation about customizing colors, which is possible (via SCSS), but there are classes such as `has-text-grey` which are hardcoded values. Should these not refer to the appropriate SCSS vars instead? (`$grey`)

**Comment by jgthms** [comment]
There’s a `$colors` and `$shades` map here: https://github.com/jgthms/bulma/blob/master/sass/utilities/derived-variables.sass

That’s where the name comes from.

**Comment by ffxsam** [comment]
@jgthms Right, but what I'm saying is that `.has-text-grey` and its related classes are hardcoded.

https://github.com/jgthms/bulma/blob/master/css/bulma.css#L1054-L1056

This means it doesn't matter what color variables or shades you set, it ignores them. Unless there's something I don't understand about the framework.

**Comment by ffxsam** [comment]
Another example I found in `bulma.css`:

```css
.panel-heading {
  background-color: whitesmoke;
  border-radius: 4px 4px 0 0;
  color: #363636;
  font-size: 1.25em;
  font-weight: 300;
  line-height: 1.25;
  padding: 0.5em 0.75em;
}
```

Why are these colors hardcoded? Could you help me understand how I'm supposed to customize this, other than just overriding the class itself? Seems like the colors should be in SCSS and referencing shades of grey..?
