### ISSUE TITLE
I want to use "field has-addons" in panel-block

### ISSUE THREAD

**Issue by belgh** [jgthms/bulma#2501]
This is about Bulma.
I'm using Bulma v0.7.4.

About panel block definition
The following is defined, but it does not apply width(100%) when using "field has-addons".

```css
.panel-block > .control {
  flex-grow: 1;
  flex-shrink: 1;
  width: 100%;
}
```

Similarly, please define the following.

```css
.panel-block > .field {
  flex-grow: 1;
  flex-shrink: 1;
  width: 100%;
}
```

thx.
