### ISSUE TITLE
fieldset styling

### ISSUE THREAD

**Issue by oupala** [jgthms/bulma#2548]
### Overview of the problem

This is a *question* about **Bulma | the Docs**.

I'm using Bulma **version** [0.7.5]
My **browser** is: Firefox 67.0.4

I am *pretty* sure this issue is **not a duplicate**

### Description

I want to style a fieldset in order to add a thin border around it, but I can't override the fieldset styling to do that. Can someone explain me how I can do that 

I've read the doc but can't figure out how to override bulma's default styling when no variables exists in bulma's documentation.

### Steps to Reproduce

See this [jsfiddle](https://jsfiddle.net/7esfjcy0/).

### Expected behavior

n/a

### Actual behavior

n/a

**Comment by svivian** [comment]
You're using `#fieldset` in the CSS which is an id selector. Use `fieldset` instead. Also the border needs a style and colour, e.g. `border: 5px solid gray`

**Comment by oupala** [comment]
You're right @svivian. I fixed the example jsfiddle, thanks for your help.

In fact my main problem was caused by importing the fontawesome scss which prevented me from inserting css after fontawesome imports:

```scss
@import "../node_modules/bulma/bulma.sass";
@import "../node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss";
@import "../node_modules/@fortawesome/fontawesome-free/scss/solid.scss"
fieldset {
  margin: 10px;
  padding: 10px;
  border: 1px solid gray;
}
```

was causing an error:

```log
=> changed: /home/user/bulma-start/_sass/main.scss
{
  "status": 1,
  "file": "/home/user/bulma-start/_sass/main.scss",
  "line": 47,
  "column": 9,
  "message": "Invalid CSS after \"fieldset\": expected 1 selector or at-rule, was \"{\"",
  "formatted": "Error: Invalid CSS after \"fieldset\": expected 1 selector or at-rule, was \"{\"\n        on line 47 of _sass/main.scss\n>> fieldset {\n\n   --------^\n"
}
```

Thanks for your help!
