### ISSUE TITLE
tiles collapse in ie11

### ISSUE THREAD

**Issue by selfagency** [jgthms/bulma#265]
### Checklist

* [X] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [X] I'm using Bulma **version** [0.1.0]
* [X] My **browser** is: Internet Explorer 11
* [X] I am sure this issue is **not a duplicate**?

### Description

Tiles collapse in IE 11.

They look fine in their first iteration above the fold.
![screenshot 2016-07-07 20 09 53](https://cloud.githubusercontent.com/assets/2541728/16673748/ef4f5908-447e-11e6-8ef9-0cf59f9deaf3.png)

Then in their second iteration, below the fold, they go bonkers.
![screenshot 2016-07-07 20 09 58](https://cloud.githubusercontent.com/assets/2541728/16673751/fb016a3e-447e-11e6-960c-667962fd9cb6.png)

It looks fine in Edge, Firefox, Chrome, Safari, and Opera on Mac and PC.

### Steps to Reproduce

```html
        <div class="stories tile is-ancestor">
          <div class="tile is-parent is-vertical">
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth radar">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=26"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>radar</h4>
                    </div>
                    <h1>Nullam quis risus eget urna mollis ornare vel eu leo</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth fashion">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=36"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>fashion</h4>
                    </div>
                    <h1>Praesent commodo cursus magna, vel scelerisque nisl consectetur et</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
          </div>
          <div class="tile is-parent is-vertical">
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth music">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=46"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>music</h4>
                    </div>
                    <h1>Donec sed odio dui</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth beauty">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=78"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>beauty</h4>
                    </div>
                    <h1>Cras mattis consectetur purus sit amet fermentum</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
          </div>
          <div class="tile is-parent is-vertical">
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth video">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=66"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>video</h4>
                    </div>
                    <h1>Fusce dapibus, tellus ac cursus commodo</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth guys">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=卐88卐"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>guys</h4>
                    </div>
                    <h1>Tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
          </div>
        </div>
        <div class="stories tile is-ancestor">
          <div class="tile is-parent is-vertical">
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth video">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=66"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>video</h4>
                    </div>
                    <h1>Fusce dapibus, tellus ac cursus commodo</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth guys">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=卐88卐"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>guys</h4>
                    </div>
                    <h1>Tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
          </div>
          <div class="tile is-parent is-vertical">
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth radar">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=26"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>radar</h4>
                    </div>
                    <h1>Nullam quis risus eget urna mollis ornare vel eu leo</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth fashion">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=36"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>fashion</h4>
                    </div>
                    <h1>Praesent commodo cursus magna, vel scelerisque nisl consectetur et</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
          </div>
          <div class="tile is-parent is-vertical">
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth music">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=46"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>music</h4>
                    </div>
                    <h1>Donec sed odio dui</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
            <div class="story tile is-child"><a href="#">
                <div class="card is-fullwidth beauty">
                  <div class="card-image">
                    <div class="figure image is-3by2"><img src="https://unsplash.it/640/360/?image=78"/></div>
                  </div>
                  <div class="card-content has-text-centered">
                    <div class="category">
                      <h4>beauty</h4>
                    </div>
                    <h1>Cras mattis consectetur purus sit amet fermentum</h1>
                    <p> <span class="is-hidden-touch">Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis.</span></p>
                    <div class="meta">1 Hour Ago &nbsp;|&nbsp; By Jane Doe</div>
                  </div>
                </div></a></div>
          </div>
        </div>
```

```scss
#stories {
  margin: 0 15px;
  max-width: 970px;
  padding: 10px 0;

  @include responsive(tablet) {
    margin: 0 25px;
  }

  @include responsive(desktop) {
    margin: 0 auto;
  }
}

.story {
  .card {
    align-self: stretch;
    border: 1px solid $black;
    box-shadow: none;
    height: 100%;
    position: relative;

    .card-content {
      color: $black;
      margin-top: 67%;
    }

    .card-image {
      left: -1px;
      position: absolute;
      top: -1px;
      width: calc(100% + 2px);

      img {
        max-width: 100%;
        transition: all 0.25s ease-in-out;
      }
    }

    h1 {
      display: inline;
      font-size: 1.4em;
      font-weight: 600;
      text-transform: capitalize;
      transition: color 0.25s ease-out;
    }

    .category {
      left: 50%;
      margin: -35px 0 1em;
      position: absolute;
    }

    .category h4 {
      background-color: $black;
      color: $white;
      display: block;
      font-weight: 800;
      left: -50%;
      margin: 0;
      padding: 5px 5px 2px;
      position: relative;
      text-transform: uppercase;
    }

    p {
      color: $gray;
      margin: 10px 0;
      overflow: hidden;
      padding-bottom: 20px;
    }

    .meta {
      bottom: 0;
      color: $mdgray;
      display: block;
      font-size: 0.9em;
      font-weight: 600;
      left: 0;
      margin: 20px auto;
      position: absolute;
      text-align: center;
      text-transform: uppercase;
      width: 100%;
    }

    &:hover {
      h1 {
        border-bottom: 2px solid;
      }
    }
  }

  @each $cat, $color in $cats {
    .#{$cat} {
      border-color: $color;

      .category h4 {
        background-color: $color;
      }

      &:hover {
        h1 {
          border-color: $color;
        }
      }
    }
  }
}
```

_Expected behavior:_ 

![screenshot 2016-07-07 19 59 07](https://cloud.githubusercontent.com/assets/2541728/16673760/139a822e-447f-11e6-8dce-7163ad1c6751.png)

_Actual behavior:_ 

![screenshot 2016-07-07 20 09 58](https://cloud.githubusercontent.com/assets/2541728/16673751/fb016a3e-447e-11e6-960c-667962fd9cb6.png)
