### ISSUE TITLE
Why did you increase controls size?

### ISSUE THREAD

**Issue by baba43** [jgthms/bulma#2675]
Just a simple question, because I'd like to understand the reason.

**Comment by jgthms** [comment]
I decided to increase it by 4px because it actually looks better as it gives more space for the text to breathe.

**Comment by baba43** [comment]
Ok, maybe you can help me out then.

You've provided an example of how to revert your change, but how can we use it?

This is my `bulma.scss`:

```
...
$body-background-color: #f8f8f8;
...
@import "../../../node_modules/bulma";

```

Now, if I add your snippet in between those lines, my build fails because `$control-border-width` and `$button-border-width` are undefined variables.

**Comment by jgthms** [comment]
You're not importing bulma correctly. Try:

```
@import "../../../node_modules/bulma/bulma.sass";
// or
@import "~bulma/bulma.sass";
// or
@import "@bulma/bulma.sass";
```

**Comment by events-jonas-chrisw** [comment]
Mine breaks too when  i import into a vue app like so:

@import "../node_modules/bulma/bulma.sass";

i get

 Undefined variable: "$control-border-width".

$control-border-width doesn't exist before I import and obviously the button and control paddings have no effect after I import.

**Comment by msonowal** [comment]
Guys
who have issues upgrade to 0.8.0
due to this add this to
just before the line
`$button-padding-vertical: calc(0.375em - #{$button-border-width});`

to have the original sizing 

```
$button-border-width: $control-border-width !default;
```

@jgthms You should update the upgrade release note

**Comment by MangelMaxime** [comment]
In case someone needs it, here is how I had to put in my project.

```scss
@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/functions";
@import "~bulma/sass/utilities/derived-variables";

$control-border-width: 1px !default; // Without this line it complains that $control-border-width doesn't exist; 1px is what is used in Bulma source code
$button-border-width: $control-border-width !default; // Without this line it complains that $button-border-width doesn't exist
$control-height: 2.25em;
$control-padding-vertical: calc(0.375em - #{$control-border-width});
$control-padding-horizontal: calc(0.625em - #{$control-border-width});
$button-padding-vertical: calc(0.375em - #{$button-border-width});
$button-padding-horizontal: 0.75em;

@import '~bulma/bulma.sass';
```
