### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by MattixNow** [jgthms/bulma#2713]
```css
details > div {
    padding-left: 0.5rem;
    margin-left: 0.2rem;
    margin-top: 0.2rem;
    border-left: solid #e7e7e7;
}
```

maybe you can add style to summary details.
![2019-11-24 19_17_21-A Pen by Mattèo](https://user-images.githubusercontent.com/32040951/69499175-9ea7ef80-0eef-11ea-9cf1-c763e6b263dd.png)
