### ISSUE TITLE
Container width

### ISSUE THREAD

**Issue by arturplo** [jgthms/bulma#2794]
Hi How to-max width div with class container is 960px?
CSS:
```css
@media screen and (min-width: 1000px)
.is-width-960px {
    max-width: 960px!important;
}
```
HTML:
```html
<div class="container is-width-960px">
...
</div>
```
is enough?
