### ISSUE TITLE
!bug not work classes is-size-[size]

### ISSUE THREAD

**Issue by AkioSarkiz** [jgthms/bulma#2884]
This is about **Bulma **

### Overview of the problem

 This is about the Bulma **CSS framework**

### Description

My css have this source:
```css
.is-size-1 {
    font-size: "none", 0 !important;
}

.is-size-2 {
    font-size: "xxs", 0.125 !important;
}

.is-size-3 {
    font-size: "xs", 0.25 !important;
}

.is-size-4 {
    font-size: "sm", 0.5 !important;
}

.is-size-5 {
    font-size: "md", 1 !important;
}

.is-size-6 {
    font-size: "lg", 2 !important;
}

.is-size-7 {
    font-size: "xl", 4 !important;
}

.is-size-8 {
    font-size: "xxl", 8 !important;
}
```

__but it's not work__

**Comment by jgthms** [comment]
How did that happen? What’s your code?

**Comment by AkioSarkiz** [comment]
i find conflict file. source:
```scss
$sizeUnit: rem;
$marginKey: 'm';
$paddingKey: 'p';
$separator: '-';
$sizes: (
    ('none', 0),
    ('xxs', 0.125),
    ('xs', 0.25),
    ('sm', 0.5),
    ('md', 1),
    ('lg', 2),
    ('xl', 4),
    ('xxl', 8),
);
$positions: (
    ('t', 'top'),
    ('r', 'right'),
    ('b', 'bottom'),
    ('l', 'left'),
);

@function sizeValue($key, $value) {
    @return if($key=='none', 0, $value + $sizeUnit);
}

@each $size in $sizes {
    $sizeKey: nth($size, 1);
    $sizeValue: nth($size, 2);

    .#{$marginKey}#{$separator}#{$sizeKey} {
        margin: sizeValue($sizeKey, $sizeValue) !important;
    }

    .#{$paddingKey}#{$separator}#{$sizeKey} {
        padding: sizeValue($sizeKey, $sizeValue) !important;
    }

    @each $position in $positions {
        $posKey: nth($position, 1);
        $posValue: nth($position, 2);

        .#{$marginKey}#{$separator}#{$posKey}#{$separator}#{$sizeKey} {
            margin-#{$posValue}: sizeValue($sizeKey, $sizeValue) !important;
        }

        .#{$paddingKey}#{$separator}#{$posKey}#{$separator}#{$sizeKey} {
            padding-#{$posValue}: sizeValue($sizeKey, $sizeValue) !important;
        }
    }
}
```

and edit import bulma before my file. It's work. Sorry, it was my problem (((
