### ISSUE TITLE
Strange transparent border for .input and .select

### ISSUE THREAD

**Issue by Grustamli** [jgthms/bulma#2927]
.input, .select elements get `border: 1px soild transparent` style by default. I expect to get colored border as shown in the docs but I can't. 
I checked the bulma.css and there are two contradicting styles with the same specifity. Chrome picks up the first one:

On line 169
```css
.button, .input, .textarea, .select select, .file-cta,
.file-name, .pagination-previous,
.pagination-next,
.pagination-link,
.pagination-ellipsis {
  ...
  border: 1px solid transparent;
  ...
}
```

On line 4318
```css
.input, .textarea, .select select {
  ...
  border-color: #dbdbdb;
  ...
}
```

### Edit:
I inspected the code for Bulma docs and it seems the styles are applied in correct order. But for me it's reversed. I use webpack to compille the sass file.
