### ISSUE TITLE
 .field-body  add align-item:center

### ISSUE THREAD

**Issue by Valar103769** [jgthms/bulma#2928]
can you add ?
```css
.field-body{
align-item:center
}
```
![image](https://user-images.githubusercontent.com/36926073/80558263-55af1680-8a0c-11ea-9002-8956432d3a1f.png)
