### ISSUE TITLE
Active tab inherits wrong style when inside hero

### ISSUE THREAD

**Issue by gragland** [jgthms/bulma#3009]
### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **0.9.0**
My **browser** is: Safari 13.1
I am sure this issue is **not a duplicate**

### Description

The active tab has the wrong text color when inside a .hero element. This can be seen in the [Bulma docs hero section](https://bulma.io/documentation/layout/hero/).
![Screen Shot 2020-06-22 at 2 51 01 PM](https://user-images.githubusercontent.com/1481077/85338910-ffa0a180-b497-11ea-9099-07a31587dbcb.png)

Another example where the tab background-color and text color will be black, so the text is completely illegible:

```html
<div class="hero is-white">
  <div class="hero-body">
    <div class="tabs is-toggle ">
      <ul>
        <li class="is-active"><a href="#">General</a></li>
        <li><a href="#">Password</a></li>
     </ul>
    </div>
  </div>
</div>
```
Screenshot:
![Screen Shot 2020-06-22 at 2 34 08 PM](https://user-images.githubusercontent.com/1481077/85338272-ce73a180-b496-11ea-8dcb-d17a2beaadd9.png)

I'm only seeing this behavior on Safari. It appears to be an issue with the following CSS taking precedence:
```css
.hero.is-white a:not(.button):not(.dropdown-item):not(.tag):not(.pagination-link.is-current), .hero.is-light strong {
color: inherit;
}
```
