### ISSUE TITLE
please namespace all classes

### ISSUE THREAD

**Issue by nimo23** [jgthms/bulma#302]
Please **namespace** all your classes with the prefix "bulma-" or "b-", because there are a lot of conflicts when using other css frameworks as well. For example, common css-class names such as .card, .panel etc are in conflict. So please namespace all the classes with "b-" ("b-card", "b-panel", etc.).

Thanks.

**Comment by jgthms** [comment]
I understand the idea, but most people only use a single css framework. I guess you could import the sass files you want, and wrap that inside a new class, and use `&-` to namespace.

Or you could use CSS modules.

But renaming everything would bring a _lot_ of noise, and I believe most users don't want that noise.

**Comment by Florian-R** [comment]
> I understand the idea, but most people only use a single css framework. I guess you could import the sass files you want, and wrap that inside a new class, and use &- to namespace.

Could you expand on this. I'm not sure to understand what you meant.

Alternatively, would you be open to a PR adding prefixes as an optional variables? Something as dumb than 

```sass
$prefix: 'my-prefix-'

.#{$prefix}input
  color: red
```

I agree that it's rather ugly but I've not done Sass since a long time, so maybe this is achievable in a prettier way.

**Comment by dacodekid** [comment]
@jgthms I currently using `prismjs` for code highlighting and it is creating classes like `number`, `tag`, etc which conflicts which results like below. If prefixing by default isn't an option, would appreciate if you consider giving an optional variable to set for those users in need.

![image](https://cloud.githubusercontent.com/assets/10047844/20281257/c89c31a4-aa7d-11e6-8564-82eaaa18e6db.png)

**Comment by nimo23** [comment]
Not Namespacing CSS-Libraries is a Anti-Pattern. It is better to namespace by default. 
.bulma-card is better than .card.

**Comment by dacodekid** [comment]
@nimo23 I too agree on this. But both `Bulma` & `PrismJS` libraries already adapted in large and I'm not sure how adding `prefix` to its would impact those.  Seems `PrismJS` also [suffering this same issue](https://github.com/PrismJS/prism/issues/6).

**Comment by jgthms** [comment]
Reopening the issue as I feel all of you make good points.

I will consider adding `$prefix` as @Florian-R suggested, and default it to an empty string: `$prefix: ""`.

**Comment by Florian-R** [comment]
@jgthms I'm pretty busy ATM, but I'll try to send you a PR for this when I can, unless someone beat me to it.

**Comment by jgthms** [comment]
No worries. I'm refactoring a lot of code. I'll add the prefix later.

**Comment by hgezim** [comment]
I submitted a PR for this. Does it take long to get it reviewed?

**Comment by yoostk** [comment]
@hgezim Did you run `$ npm run deploy` as documented in [PR template](https://raw.githubusercontent.com/jgthms/bulma/master/.github/PULL_REQUEST_TEMPLATE.md)?

**Comment by hgezim** [comment]
@yoostk, I did but `css/bulma.css` got some weird changes.

Nothing should change in the deployed css file. `$prefix` is set to blank by default.

Here's the diff:

```
diff --git a/css/bulma.css b/css/bulma.css
index 6703f21..4bd5a0b 100644
--- a/css/bulma.css
+++ b/css/bulma.css
@@ -3222,7 +3222,6 @@ a.box:active {
 .level-left {
   -webkit-box-align: center;
       -ms-flex-align: center;
-              -ms-grid-row-align: center;
           align-items: center;
   -webkit-box-pack: start;
       -ms-flex-pack: start;
@@ -3246,7 +3245,6 @@ a.box:active {
 .level-right {
   -webkit-box-align: center;
       -ms-flex-align: center;
-              -ms-grid-row-align: center;
           align-items: center;
   -webkit-box-pack: end;
       -ms-flex-pack: end;
@@ -3264,7 +3262,6 @@ a.box:active {
 .level {
   -webkit-box-align: center;
       -ms-flex-align: center;
-              -ms-grid-row-align: center;
           align-items: center;
   -webkit-box-pack: justify;
       -ms-flex-pack: justify;
@@ -3817,7 +3814,6 @@ a.box:active {
   top: 0;
   -webkit-box-align: center;
       -ms-flex-align: center;
-              -ms-grid-row-align: center;
           align-items: center;
   display: none;
   -webkit-box-pack: center;
@@ -4030,7 +4026,6 @@ a.nav-item.is-tab.is-active {
 .nav-right {
   -webkit-box-align: stretch;
       -ms-flex-align: stretch;
-              -ms-grid-row-align: stretch;
           align-items: stretch;
   -ms-flex-preferred-size: 0;
       flex-basis: 0;
@@ -5617,7 +5612,6 @@ label.panel-block:hover {
 .columns.is-vcentered {
   -webkit-box-align: center;
       -ms-flex-align: center;
-              -ms-grid-row-align: center;
           align-items: center;
 }

@@ -5640,7 +5634,6 @@ label.panel-block:hover {
 .tile {
   -webkit-box-align: stretch;
       -ms-flex-align: stretch;
-              -ms-grid-row-align: stretch;
           align-items: stretch;
   display: block;
   -ms-flex-preferred-size: 0;
```

**Comment by yoostk** [comment]
Because the same change can be seen in b2440df07b69b59c95de25479006f509555caefb, the update to 0.3.1 (the commit pushed after your PR), I guess that's a normal behavior.

**Comment by hgezim** [comment]
There's still a conflict even though I did a `git pull` from master and then rebased with master from my branch.

**Comment by yoostk** [comment]
It might be better to wait for the maintainer's response 😅

**Comment by jgthms** [comment]
https://github.com/jgthms/bulma/pull/511#issuecomment-289295677

**Comment by fgarcia** [comment]
> most people only use a single css framework

That is exactly what I want every time I start a project. However every single time I deal with a project that survives longer than a year, I get frustrated when all the the sexy looking names are taken by a framework

Nowadays one of my biggest concerns is finding easy to cherry-pick frameworks. 

CSS Modules are great, but not the best solution. They are only good for cleaning the global namespace

While prototyping or applying minor modifications, I love having non prefixed selectors. But I love having those under my control. Maybe a sass mixing approach??

In any case I do not like the "choose your own prefix" approach. I do believe it is far more valuable having two releases: one with and one without prefixes. That way we could get hard stats/data on what people want. Although I fear that what people initially desire/want is very different to what they need in long term projects

**Comment by ZeroDragon** [comment]
I'd love a way to prefix bulma and generate a custom build just like jquery-ui used to to way back in the day. That way the core of bulma stays clean for new projects with only one CSS framework but can create a custom build with bulma restricted to a single container class.

In my case I want to create a site plugin that inserts a chat to any existing webpage. And will love to have bulma in the chat but not outside of it. Hope this helps a little

![image](https://user-images.githubusercontent.com/616185/32672506-ee41a286-c610-11e7-8233-90ed72f1901f.png)

**Comment by BarFoo** [comment]
In my opinion, the right way  to prefix css classes, should you need to, is during the build process. I don't think it is right for Bulma to prefix all classes with something like `bulma-`, it is ugly and non portable in my  opinion.

**Comment by ZeroDragon** [comment]
you are correct, by default, prefixin all its ugly and has several disadvantages. I just posted an example of an online builder, in that way the core is intact and could create a custom scoped build for any purposes, This might actually can be my next weekend project. I just did a PoC using stylus:
```
const stylus = require('stylus')
const request = require('request')

request.get(
  'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.1/css/bulma.css',
  (err, data, body) => {
    if (err) throw err
    const styl = `
      .pwnChat{
        ${body}
      }
    `
    stylus(styl).render((errStylus, css) => {
      console.log(css)
    })
  }
)
```
This outputs something like this:
![image](https://user-images.githubusercontent.com/616185/32675620-1552a12a-c61d-11e7-9f42-524fd001010a.png)

**Comment by andreujuanc** [comment]
Personally I think scopes are the way to go. :)

**Comment by jazoom** [comment]
I don't intend to use multiple CSS frameworks, but not prefixing Bulma means one must know ALL Bulma styles before using Bulma. Right now I'm starting using Bulma for a new project and I have Bulma styling applied to elements that I don't want Bulma styling applied to, simply because of the class I used.

Even once you know all styles, you still always have to be careful when you use them.

IMHO it's far cleaner and more portable to just stick a "b-" at the front of all styles. Then you don't need to use silly classes for things in a project just to avoid summoning Bulma.

And I'd hate to try integrating Bulma with an already-established project, like some poor souls here seem to need to do. Surely all projects already have classes like "title", "hero", "card", "button", etc.

**Comment by yury-sannikov** [comment]
@jazoom looks like @hgezim did a great job adding prefixes to Bulma. I have the same issue. Any real word project has a long history and has a lot of libraries. I'm considering to get rid of Bulma due to lack of namespace feature.

**Comment by UiCandy** [comment]
+1 Please consider name-spacing.

I'll beat the dead horse one more time:

Imagine you're trying to convince your team why this is the best framework to pick for our next project and propose to implement the grid system on a module in an existing project as a PoC.

The existing grid uses a `.container` class multiple times at diff levels. 

It's impossible to implement without side effects

**Comment by kWhittington** [comment]
At least providing an option would be nice, you don't have to make the namespacing required.

My team would like to switch to `Bulma` from `Bootstrap` `v2.3.2` but the conflicts + the work it's going to take to manually isolate all `Bootstrap` has kept that dead in the water for a month or more now.

**Comment by moeloubani** [comment]
Wanted to use Bulma for a WP plugin today but I couldn't because any site that activates the plugin will for sure have CSS conflicts. +1 for this feature!

**Comment by dsebastian** [comment]
Shame this wasn't implemented by now, it's not always a case of "you start a project with a framework and keep it for the rest of it's life". Imagine the case of older projects done with Bootstrap where the dev team would like to switch to Bulma for some new screens, without having to rewrite the entire application.
I'd say a prefix var and 2 lines in the documentation should go far on this one.

**Comment by rolandalla** [comment]
Still  waiting for this implementation ...

**Comment by adonig** [comment]
I went with Pure because of this issue :-/

**Comment by michaelguild13** [comment]
We want to use bulma on a lot of our washington post apps but we can't do this unless you guys support prefix due to legacy conflicts.

**Comment by andreujuanc** [comment]
Guys, I wrap imports within a `.bulma { }`  , and it works for me. 

Based on https://github.com/jgthms/bulma-start/blob/master/_sass/main.scss 
My main.scss looks like this:

```scss
@charset "utf-8";

// Customization

// You can easily customize Bulma with your own variables.
// Just uncomment the following block to see the result.


// 1. Import the initial variables
@import "../../node_modules/bulma/sass/utilities/initial-variables";
@import "../../node_modules/bulma/sass/utilities/functions";
@import "../../node_modules/bulma/sass/base/minireset";


// 2. Set your own initial variables
// Add pink and its invert
$teal:    hsl(10, 70%, 61%);
$teal-invert: findColorInvert($teal);
$lightbrown: hsl(43, 27%, 82%);
$lightbrown-invert: findColorInvert($lightbrown);

// Update the sans-serif font family
$family-sans-serif: "Helvetica", "Arial", sans-serif;

 
// 3. Set the derived variables
// Use the new pink as the primary color
$primary: $teal;
$primary-invert: $teal-invert;

$link: $lightbrown;
$dropdown-content-arrow: $teal;
$button-background-color: $lightbrown;


$section-padding: 0.9rem 0.8rem;//DEFAULT 3rem 1.5rem

@import "../../node_modules/bulma/sass/utilities/_all.sass";
//@import "../../node_modules/bulma/sass/utilities/derived-variables.sass";

$addColors: (
    "teal":($teal, $teal-invert),
    "lightbrown": ($lightbrown, $lightbrown-invert)
);
$colors: map-merge($colors, $addColors);



.bulma {
    @import "../../node_modules/bulma/sass/base/generic";
   // 4. Import the rest of Bulma
    @import "../../node_modules/bulma/bulma";
    @import "formoverride.sass";
    //bulma extensions
    @import '../../node_modules/bulma-quickview/dist/bulma-quickview.sass'; 
    @import 'bulma.extensions.tooltip';

    .dropdown, 
    .dropdown .dropdown-trigger,
    .dropdown .dropdown-trigger button {
        display: flex;
        flex: auto;
    }

    .dropdown .dropdown-trigger button {
        justify-content: space-between;
    }

    @import '../../node_modules/bulma-calendar/src/sass/index.sass';
}

```
