### ISSUE TITLE
Support for css variables

### ISSUE THREAD

**Issue by kolaente** [jgthms/bulma#3028]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I think using css variables in bulma would greatly enhance the framework since they allow things like [easier theming with less boilerplate](https://codyhouse.co/blog/post/css-custom-properties-vs-sass-variables) - other more "mainstream" frameworks like [bootstrap](https://getbootstrap.com/docs/4.0/getting-started/theming/#css-variables) are also using them.

CSS variables can be [considered stable to use](https://caniuse.com/#feat=css-variables) since most browsers seem to support them since a while now.

I've looked at #2342 which seems to be related to this but is more precisely about dark themes while I hope this issue is a more general look at css variables in bulma - I wasn't able to find a broader issue about this topic. Please tell me if I should rather close this issue.

**Comment by piotrpog** [comment]
agreed, nowadays custom property support is must-have.

**Comment by jgthms** [comment]
It is planned. I have a few branches working on it. I only need to find the best way to implement it. There are a few options.

**Comment by kolaente** [comment]
@jgthms That's great to hear! Anything we could help you with?

**Comment by jgthms** [comment]
If you could provide an example of how you would use CSS variables, or how you already use them, that would be great.

**Comment by kolaente** [comment]
I would use css variables for theming my application (classic use case would be a light/dark theme). CSS variables let me do stuff like this: 

```css
:root, [data-theme="default"] {
  --color-primary: blue;
  --color-bg: white;
}

[data-theme="dark"] {
  --color-primary: red;
}

body {
  background-color: var(--color-bg);
  color: var(--color-contrast-high);
}
```

That way, when a user changes their theme I (or rather, a js snippet) would add a `data-theme="dark"` to the `<body>` element and call it a day.

I know I achieve the same with sass or less but that would require me to have essentially two versions of the whole site stylesheet, which can get quite big.
