### ISSUE TITLE
Bulma centered navbar mobile issues

### ISSUE THREAD

**Issue by karipov** [jgthms/bulma#3055]
This is about **Bulma**. I need help with what is possibly a bug. I've been able to reproduce it only on mobile Safari

### Overview of the problem

I'm using Bulma **version** [0.8.2]
My **browser** is: Safari iOS (iPhone 7)

### Description

I'm creating a navbar for a current project in react (create-react-app). I'm using the Bulma framework for all css-related things. The current problem lies in the navigation bar, the elements of which should together be centered and visible on mobile.

While this isn't possible with Bulma alone, I used some scss modifications I've found to make it somewhat work:

#### App.scss Stylesheets
```css
.navbar-start { // fixes is-expanded on the navbar items
    flex-grow: 1;
    flex-shrink: 1;
    display: flex;
    text-align: center;
}

.navbar-item {
    border-style: solid;
    border-color: black;
    border-width: medium;
}

#center-item {
    border-right-width: 0;
    border-left-width: 0;
}
```

#### HTML (navbar only)
```html
<div>
  <nav className="navbar is-dark" role="navigation" aria-label="main navigation">
    <div className="container has-text-centered ">
      <div className="navbar-menu">
        <div className="navbar-start">
          <Link className="navbar-item is-expanded has-text-weight-semibold is-size-5" to="/">/home</Link>
          <Link id="center-item" className="navbar-item is-expanded has-text-weight-semibold is-size-5" to="/visual">/visual</Link>
          <Link className="navbar-item is-expanded has-text-weight-semibold is-size-5" to="/about">/about</Link>
        </div>
      </div>
    </div>
  </nav>
</div>
```
Finally, to make this horizontal navbar visible on mobile, I've also modified a bulma variable according to [this](https://github.com/jgthms/bulma/issues/1445) in the scss file.: `$navbar-breakpoint: 0`.

### Actual behavior

![Image](https://i.stack.imgur.com/LGVrL.jpg)

### Expected behavior

There should be no empty space.

### Additional details
Live website: http://51.15.246.99
Project source code: https://github.com/visual-cs/site
