### ISSUE TITLE
Variable gap must not use CSS variables

### ISSUE THREAD

**Issue by scriptcoded** [jgthms/bulma#3181]
This is about **Bulma**.

This is a thought about the implementation of the variable column gap feature.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.9.1]

I am sure this issue is **not a duplicate**

### Description

The [current implementation](https://github.com/jgthms/bulma/blob/0a1ef3c4fbf05d503ac626c7f53b1b7a93ac350b/sass/grid/columns.sass#L476-L513) of the variable gap feature uses CSS variables. While this might make the resulting CSS a bit more compact, I don't think it's strictly necessary.

Something like the following should work just fine. I'm not well versed in SASS, so this is in SCSS. Also, breakpoints aren't included.

```scss
.columns.is-variable {
  @for $i from 0 through 8 {
    &.is-#{$i} {
      margin-left: $i * -0.25rem;
      margin-right: $i * -0.25rem;

      & > .column {
        padding-left: $i * 0.25rem;
        padding-right: $i * 0.25rem;
      }
    }
  }
}
```

Skipping CSS variables would mean IE browser compatibility. Although pretty much every other browser supports CSS variables, the more compatibility the better IMO.
