### ISSUE TITLE
Feature request: add a variable to control the loader colour

### ISSUE THREAD

**Issue by unikitty37** [jgthms/bulma#3228]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.9.0] (via Buefy, which hasn't updated to 0.9.1 yet)

I am sure this issue is **not a duplicate**

### Description

The colour of the loader animation is fixed in https://github.com/jgthms/bulma/blob/30af49b35f2f5652e50ae968f87ea3e939f7346a/sass/utilities/mixins.sass#L252

It can be overridden, but it requires spelunking through the source and the web inspector to find out how. (Hopefully, this issue will at least help anyone else who's trying to work it out…)

It would be much easier if there was a `$loader-color` variable which, for compatibility, should default to the current value of `$grey-lighter`.

Currently, this is necessary:

```css
  .loading-background .loading-icon:after {
    border-bottom-color: #f00;
    border-left-color: #f00;
  }
```
