### ISSUE TITLE
Feature Request: is-borderless for remove borders

### ISSUE THREAD

**Issue by vjik** [jgthms/bulma#3235]
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.1
 
Add 
```css
.is-borderless { border: 0}
```
