### ISSUE TITLE
Printing radio buttons and checkboxes

### ISSUE THREAD

**Issue by LeoDupont** [jgthms/bulma#3271]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.1 (embedded in Buefy 0.9.4 for Vue)
My **browser** is: Vivaldi, Edge, Chrome

### Description

The radios and checkboxes are checked with a background effect, which doesn't get printed by default by browsers.
So only the border gets printed. 
And if you print in black & white, it is impossible to tell whether an input is checked or not.

A workaround can be adding/editing the `:before` `content` like so:
```css
@media print {
    .b-radio.radio input[type=radio]:checked + .check:before {
        content: "X";
        transform: scale(1.5);
        width: 0;
        height: 14pt;
    }
    .b-checkbox.checkbox input[type=checkbox]:checked + .check:before {
        content: "X";
    }
}
```

But it would be nice to have a built-in fallback (and better looking than mine :P).
