### ISSUE TITLE
Extending the margin modifier

### ISSUE THREAD

**Issue by eypsilon** [jgthms/bulma#3286]
Since margins can also contain minus values, appropriate modifiers would be useful to have.

```css
.m--1 { margin:-.25rem }
.m--2 { margin:-.5rem }
```
