### ISSUE TITLE
$background is used before initialization

### ISSUE THREAD

**Issue by wtho** [jgthms/bulma#3287]
This is a bug about **Bulma**.

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.2
This is a **Sass** issue: I'm using version 1.32.8

### Description
In `utilities`, bulma loads `functions` before `derived-variables`. It uses the variable `$background` in one of the functions (`findLightColor`) AND [calls the function](https://github.com/jgthms/bulma/blob/f26b871321a13ff2ce3f6270eec9b9585527d3b7/sass/utilities/derived-variables.sass#L26) in L26 in `derived-variables` before [initializating `$background`](https://github.com/jgthms/bulma/blob/f26b871321a13ff2ce3f6270eec9b9585527d3b7/sass/utilities/derived-variables.sass#L52) in L52 in `derived-variables`. This will lead to an error if a variable is not set to a color (which it might in weird edge case).

### Steps to Reproduce
Create `styles.sass`:
```
#{":root"}
  --my-green: rgb(72, 255, 0)
$primary: var(--my-green)
@import './node_modules/bulma/bulma'
```
Run:
```
npm i -S bulma sass
./node_modules/sass styles.scss
```
### Expected behavior
The compilation should pass.

Independent of bulma not supporting non-compile-time-colors, it should still not use variables which are not set yet.

This should be solvable by just rearranging the variables in `derived-variables`.

### Actual behavior
Error message:
```
Error: Undefined variable.
   ╷
91 │   @return $background
   │           ^^^^^^^^^^^
   ╵
  node_modules/bulma/sass/utilities/functions.sass 91:11          findLightColor()
  node_modules/bulma/sass/utilities/derived-variables.sass 26:17  @import
  node_modules/bulma/sass/utilities/_all.sass 6:9                 @import
  node_modules/bulma/bulma.sass 3:9                               @import
  styles.sass 6:9                                                 root stylesheet
```

**Comment by lexprimost** [comment]
same problem here, did you find a solution?

**Comment by wtho** [comment]
A workaround is to declare the variable before loading bulma.

**Comment by Dias1c** [comment]
Sorry for my english. 
So i had same error when use css vars

Example code which throws error:
```scss
@charset "utf-8";
@import "../../../node_modules/bulma/sass/utilities/initial-variables";
@import "../../../node_modules/bulma/sass/utilities/functions";

:root {
   --color-b-primary: #000000;
}
$primary:  var(--color-orange);
//              ^ this trhows error

@import "../../../node_modules/bulma/bulma.sass";
```

So for me helped removes css vars, and create variables as in `SASS`
```scss
@charset "utf-8";
@import "../../../node_modules/bulma/sass/utilities/initial-variables";
@import "../../../node_modules/bulma/sass/utilities/functions";

$color-b-primary: #000000;
$primary:  $color-orange;

@import "../../../node_modules/bulma/bulma.sass";
```
