### ISSUE TITLE
First image in card not used is-rounded if required

### ISSUE THREAD

**Issue by stanolacko** [jgthms/bulma#3302]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.9.2].

### Description

When image used in Card and on image is "is-rounded" helper, then image is not rounded on top borders.

### Steps to Reproduce

```html
<div class="card">
	<div class="card-image" style="position:relative; margin-bottom: 1.5rem">
		<div class="image is-96x96">
			<img class="is-rounded lazyload" style="border: 5px solid white;" alt="10Geek" src="URL">
		</div>
	</div>
</div>
```
### Expected behavior

Image will be rounded like in previous Bulma versions

### Actual behavior

Image is not rounded.

CSS applied:
```css
.card-image:last-child img {
    border-bottom-left-radius: 0.25rem;
    border-bottom-right-radius: 0.25rem;
}
.card-image:first-child img {
    border-top-left-radius: 0.25rem;
    border-top-right-radius: 0.25rem;
}
```
CSS for is-rounded image is not applied:
```css
.image img.is-rounded {
    border-radius: 290486px;
}
```
Sollution?
**A.**
```css
.image img.is-rounded {
    border-radius: 290486px !important;
}
```
**B**
```css
.card-image:last-child img:not(.is-rounded) {
    border-bottom-left-radius: 0.25rem;
    border-bottom-right-radius: 0.25rem;
}
.card-image:first-child img:not(.is-rounded) {
    border-top-left-radius: 0.25rem;
    border-top-right-radius: 0.25rem;
}
```
**C**
```css
.card-image:last-child img.is-rounded {
    border-bottom-left-radius: 290486px;
    border-bottom-right-radius: 290486px;
}
.card-image:first-child img.is-rounded {
    border-top-left-radius: 290486px;
    border-top-right-radius: 290486px;
}
```

Each of possible possultions have pros & cons. But I think that 290486px is in Sass variable $radius-rounded, than solution **C** will be the best.
