### ISSUE TITLE
Undefined variable on customization

### ISSUE THREAD

**Issue by lesar** [jgthms/bulma#3327]
This is about **Bulma 0.9.2**.  
Is it about Bulma: yes  
Is it a bug: yes I think so  
Is it  a browser bug: no  

### Overview of the problem

This is about the Bulma **CSS framework** : but not sure, it can be about a rollup-plugin or sass
I'm using Bulma **version** [0.9.2]  
My **browser** is: ff 88
This is a **Sass** issue: I'm using version [1.32.12]
I am sure this issue is **not a duplicate**? No! I have found some bug like this but no solution. I'm not sure the bug was due to my particularity configuration so in this case is not a duplicate   

### Description

I use rollup to compile my project and this is a my package.json bit:  
```json
  "devDependencies": {
    "@iconify/json": "^1.1.341",
    "@iconify/json-tools": "^1.0.10",
    "@rollup/plugin-alias": "^3.1.2",
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-node-resolve": "^13.0.0",
    "@rollup/plugin-replace": "^2.4.2",
    "@rollup/plugin-run": "^2.0.2",
    "@types/dotenv-flow": "^3.1.0",
    "@types/node": "^15.0.2",
    "bulma": "^0.9.2",
    "eslint": "^7.26.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "fastify-cli": "^2.11.0",
    "gulp": "^4.0.2",
    "inferno-devtools": "^7.4.8",
    "postcss": "^8.2.15",
    "postcss-modules": "^4.0.0",
    "rollup": "^2.47.0",
    "rollup-plugin-copy": "^3.4.0",
    "rollup-plugin-delete": "^2.0.0",
    "rollup-plugin-postcss": "^4.0.0",
    "rollup-plugin-terser": "^7.0.2",
    "sass": "^1.32.12",
    "snazzy": "^9.0.0",
    "tap": "^15.0.9"
  }
```
to compile css I use  
postcss: 8.2.15  
and  
rollup-plugin-postcss: 4.0.0  

on rollup.config.js I use this plugin to compile:  
```javascript
//  ...
    , postcss({
      extract: '/deploy-path/my.css'
      , extensions: ['.scss', '.sass']
      , use: ['sass']
    })
// ...
```
  
Inside /develop-path/my.scss:  
```scss
@charset "utf-8";

// custom variable here
// import from bulma
.colorred { color: red; }

// Fonts
@import url('https://fonts.googleapis.com/css2?family=Roboto&family=Source+Sans+Pro&display=swap');
// $title-family: "Source Sans Pro", "Roboto", BlinkMacSystemFont, -apple-system, "Segoe UI", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif !default;
$family-sans-serif: "Roboto", BlinkMacSystemFont, -apple-system, "Segoe UI", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif !default;

// Logo
$navbar-item-img-max-height: 4rem;
$navbar-height: 5rem;

$body-background-color: #181818;
$primary: #5F870D;
$footer-background-color: #333333;
$link-over: $light;

@import "~bulma/sass/utilities/_all";
@import "~bulma/sass/base/_all";
@import "~bulma/sass/elements/_all";
@import "~bulma/sass/form/_all";
@import "~bulma/sass/components/_all";
@import "~bulma/sass/grid/_all";
@import "~bulma/sass/helpers/_all";
@import "~bulma/sass/layout/_all";
```

### Steps to Reproduce
After write the project you can do:  
npm run build  

### Expected behavior
clean compilation

### Actual behavior

> [!] (plugin postcss) Error: Undefined variable.
> 22 | $link-over: $light;
> ____________^^^^^^

Someone can help?  
If it is not related to Bulma let me know.
best regards,  
Leonardo
