### ISSUE TITLE
I am not able to get `table is-hoverable` to work

### ISSUE THREAD

**Issue by zemian** [jgthms/bulma#3374]
Hi, I am not able to get `table is-hoverable` to work. I don't see any affect when I added to my table. Is it suppose to hightlight a row when user hover a row? But it's doing nothing. (I checked the doc: https://bulma.io/documentation/elements/table/ example there and it too doesn't do anything). Did I miss something?

But if I add both of these modifier `table is-hoverable is-striped`, the result is not highlighting every other rows. But instead I get every row highlighted only when hover. This behavior seems odd to me. And not what I expected from reading the doc.

What I expected them to do is the `is-striped` to highlight every other rows regardless of hover or not. And `is-hoverable` will hightlight (with different color) when user hover on each row.

Am I doing something wrong here? 

Here is a simple example: using Bulma `0.9.3`

https://codepen.io/zemian/pen/NWjxydV

**Comment by erickarugu** [comment]
Hi Zemian, from what I understand, ```is-striped``` adds a highlight on every "even" row, that is```tr```. From the example you have given on Codepen this the styling being applied on every even row that is not selected:
```css
.table.is-striped tbody tr:not(.is-selected):nth-child(even) {
    background-color: #fafafa;
}
```
And once you hover over the row, the following css styling is applied:
```css
.table.is-hoverable.is-striped tbody tr:not(.is-selected):hover:nth-child(even) {
    background-color: whitesmoke;
}
```
I hope this is the clarification you were seeking.
