### ISSUE TITLE
Empty selector not working

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [jgthms/bulma#3405]
I want to make the notification disappear when there is no text. How can I make the following work?

```css
.notification {
  &:empty {
    display: none !important;
  }
}
```
I want to have the similar behaviour in Bulma notification as Bootstrap alert.

[Bootstrap Alerts](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp)
