### ISSUE TITLE
Flexbox helpers : is-flex-gap-* proposal

### ISSUE THREAD

**Issue by fpassaniti** [jgthms/bulma#3414]
This is about **Bulma**.

It's a feature proposal

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.9.1]

### Description

I'm using flexbox helpers pretty often and only one thing is missing that force me to define classes and add specific CSS to my code is the flex gap ! 

It would be really useful to take advantage of $spacing-values to define a variety of gaps for flexbox helper.

Technically, it would be as simple as adding the equivalent of this loop in flexbox helper: 

```scss
$spacing-values: ("0": 0, "1": 0.25rem, "2": 0.5rem, "3": 0.75rem, "4": 1rem, "5": 1.5rem, "6": 3rem) !default;

@each $name, $value in $spacing-values {
  .is-flex-gap-#{$name} {
    gap: $value !important;
  }
}
```

to generate helpers like `is-flex-gap-0` to `is-flex-gap-6`

Resulting example 
```html
<header class="modal-card-head is-flex-direction-column is-align-items-flex-start is-flex-gap-4">
            <div class="is-flex is-align-items-center is-justify-content-space-between is-flex-gap-2">
```

What do you think about this upgrade ? If it makes sens, I can propose a PR if you want. Let me know.
