### ISSUE TITLE
is-disabled / disabled not working for pagination

### ISSUE THREAD

**Issue by omichel** [jgthms/bulma#3449]
### Overview of the problem

This is a bug about **Bulma and the Docs**. It's not a browser bug. I'm using Bulma **version** 0.9.3.

### Description

The [bulma doc about button](https://bulma.io/documentation/elements/button/) says the `is-disabled` class is deprecated in favor of the `disabled` attribute, which is fine. But the [Bulma doc about pagination](https://bulma.io/documentation/components/pagination/) still refers to the `is-disabled` class which has actually no effect. We should replace it with the `disabled` attribute and add the following CSS rule in Bulma:
```css
nav.pagination > a[disabled] {
  background-color: #fff;
  border-color:#dbdbdb;
  box-shadow: none;
  opacity: 0.5;
  cursor: not-allowed;
}
```
