### ISSUE TITLE
Bug? Card with an overlay, loses bottom round corners

### ISSUE THREAD

**Issue by AviranAbady** [jgthms/bulma#3451]
### Overview of the problem

Bulma framework issue.
Not browser related, tested on both Firefox and Chrome.
Bulma latest, version 0.9.3,

### Description

When using a `card` with a `card-image` in it, when adding an overlay (`is-ovelay`) the bottom round corners are losing their 'roundness'.

### Steps to Reproduce

The following codepen demonstrates the issue: https://codepen.io/avirancodepen/pen/NWaKbQo

### Expected behavior

4 round corners

### Actual behavior

2 round corners

**Comment by jgthms** [comment]
It's because the border-radius is only applied if the `card-image` is the last child:

![image](https://user-images.githubusercontent.com/1254808/143957372-69f193cf-0b2f-414d-9736-c17c4a4a11ab.png)

You can fix it by adding your own CSS:

```css
.card-image img {
    border-bottom-left-radius: 0.25rem;
    border-bottom-right-radius: 0.25rem;
}
```
