### ISSUE TITLE
custom colors and theming

### ISSUE THREAD

**Issue by victorpi463** [jgthms/bulma#3590]
### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.9.4] 
My **browser** is: chrome 
This is a **Sass** issue: I'm using version [7.0.3] 

### Description

When I try to add a variable to a custom color, the node sass command doesn't generate the new custom color classes,
but it workds when I add a color(string or hex value).
### Steps to Reproduce

1. follow the customisation with https://bulma.io/documentation/customize/with-node-sass/
2. add the following properties in the customstyle.scss
```scss
@charset "utf-8";


:root {
    --primary: red;
    --secondary: #068295;
}

body[class="light"] {
    --primary: #F7A800;
    --secondary: #068295;
}

body[class="dark"] {
    --primary: blue;
    --secondary: #068295;
}

$primary: var(--primary); // this works 
$background: blue;
$text-strong: red;

// $secondary: #8BC91D; // this works but without theming
$secondary: var(--secondary); // this doesn't work 
$secondary-invert: findColorInvert($secondary) !default;

$custom-colors: (
    "secondary":($secondary, $secondary-invert),
);

@import "../node_modules/bulma/sass/utilities/_all.sass";
@import "../node_modules/bulma/sass/base/_all.sass";
@import "../node_modules/bulma/sass/elements/button.sass";

```

### Expected behavior

it should generate, like with the primary variable, classes with the propertie var().
### Actual behavior

it doesn't generate the custom colors classes properties when the custom color is passed through a variable
