### ISSUE TITLE
Bulma hero does not play well for tabs within a box.

### ISSUE THREAD

**Issue by AlexisTM** [jgthms/bulma#3593]
This is about **Bulma CSS bug**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.4
My **browser** is: Firefox 107.0
I am sure this issue is **not a duplicate**

### Description

`tabs` within a `box` within a `hero-info` is not showing correctly. 

### Steps to Reproduce

Following is a CodePen to reproduce it: the top one is the default behaviour, the bottom one has some extra CSS.

https://codepen.io/AlexisTM/pen/abKEbXr

To overcome the issue, I added: 

```css
section.hero.is-info .tabs li.is-active a {
    color:#FFFFFF !important;
    background-color: #485fc7 !important;
}
```

The added section in front is to be prioritized against the following Bulma lines: (It was not `!important` at 0.7.4)

```css
.hero.is-info .tabs li.is-active a {
  color: #3e8ed0 !important;
  opacity: 1;
}
```

### Expected behavior

![image](https://user-images.githubusercontent.com/6976744/202858355-cc92a5fa-f617-41aa-9c70-fd9c4cb8772f.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/6976744/202858339-5c006946-d852-48a4-8827-340b8a07f84f.png)
