### ISSUE TITLE
Labels that wrap their input fields

### ISSUE THREAD

**Issue by Merott** [jgthms/bulma#360]
Tag your issue accordingly:
- is it about Bulma or about the Docs? Bulma
- is it a bug/feature/question or do you need help? A bug maybe, but more of a design limitation.
### Checklist
- [x] This is about the Bulma **CSS framework**
- [x] I'm using Bulma **0.2.3**
- [x] I am sure this issue is **not a duplicate**
### Description

Currently one can apply styles to form `label` elements by applying the `label` class as such:

``` html
<label class="label">Name</label>
<p class="control">
  <input class="input" type="text" placeholder="Text input">
</p>
```

Problem is, a `label` element should have a `for` attribute that points to some input's `id`, so it has to be written like this:

``` html
<label for="name" class="label">Name</label>
<p class="control">
  <input id="name" class="input" type="text" placeholder="Text input">
</p>
```

But also, it's common practice to wrap input elements inside of the `label` element, so that we don't have to maintain some `id` attribute, and we'd also avoid the potential of having duplicate IDs on a page:

``` html
<label class="label">
  Name
  <p class="control">
    <input class="input" type="text" placeholder="Text input">
  </p>
</label>
```

Currently this is how the `label` class is styled:

``` css
.label {
    color: #363636;
    display: block;
    font-weight: bold;
}

.label:not(:last-child) {
    margin-bottom: 5px;
}
```

The problem is, the `margin-bottom` won't work with the above HTML, and the label _Name_ won't be spaced. We could move the `label` class from the actual `label` element to a `span` within, but then the `:not(:last-child)` pseudo class won't prevent the margin from being applied to the last `label` element.

``` html
<label>
  <span class="label">Name</span>
  <p class="control">
    <input class="input" type="text" placeholder="Text input">
  </p>
</label>
```

---

Sorry for the long post, but here is my proposed solution, which as far as I see, won't break existing use cases but also covers for the above:

``` css
.label {
    color: #363636;
    display: block;
    font-weight: bold;
}

/* exactly same as before, but added :not(label) parent condition */
:not(label) > .label:not(:last-child) {
    margin-bottom: 5px;
}

/* could be combined with the above selector, but it's separate for clarity */
label:not(:last-child) > .label {
    margin-bottom: 5px;
}
```

Let me know your thoughts, and I'd also be happy to make a PR for it.
