### ISSUE TITLE
Feature request: Add style rules for disabled dropdown links

### ISSUE THREAD

**Issue by erbsland-dev** [jgthms/bulma#3682]
This is about **Bulma**. 

### Description

This is about the Bulma **CSS framework**. I'm using Bulma **version** 0.9.4.

Dropdown entries do not support a disabled state. Please add a method to create dropdown entries that are in a disabled state.

Neither `<a class="dropdown-item is-disabled">...</a>` nor `<a class="dropdown-item" disabled>...</a>` works.

### Example Solution:

```css
a.dropdown-item[disabled] {
    color: $grey;
    cursor: default;
    pointer-events: none;
}
```
