### ISSUE TITLE
Switch component

### ISSUE THREAD

**Issue by stsrki** [jgthms/bulma#3764]
Hello. Is there a plan to work on the switch component?

![image](https://github.com/jgthms/bulma/assets/900302/63169e0a-6c76-4ae9-8c4f-a6ef89022b65)

**Comment by jgthms** [comment]
There is not. It's fairly standard to design but it would require JavaScript to work.

**Comment by jgthms** [comment]
Yes but that's more of a hack. 

Also, on mobile devices, you can drag that control. If you want to replicate that UX, you require Javascript. 

Some other Bulma components require a bit of JavaScript so I'll think about it.

**Comment by stsrki** [comment]
> Some other Bulma components require a bit of JavaScript so I'll think about it.

Appreciate it.

**Comment by digitigradeit** [comment]
@jbrazeau haha you beat me to it!

I was working on it as well. it's remarkable how similar the code is.. Mine loosely based on the [/Wikiki/bulma-switch](https://github.com/Wikiki/bulma-switch/tree/master) version.

with additional mixin support.

```css
@use "sass:math";
@use "sass:list";

@use "../node_modules/bulma/sass/utilities/initial-variables" as iv;
@use "../node_modules/bulma/sass/utilities/derived-variables" as dv;
@use "../node_modules/bulma/sass/utilities/css-variables" as cv;
@use "../node_modules/bulma/sass/utilities/extends" as ext;
@use "../node_modules/bulma/sass/utilities/controls" as ctrl;

$switch-background: iv.$grey-light !default;
$switch-background-active: dv.$primary !default;
$switch-colors: dv.$colors !default;
$switch-outline-width: ctrl.$control-border-width !default;
$switch-margin: 1rem !default;
$switch-paddle-background: iv.$white !default;
$switch-paddle-background-active: iv.$white !default;
$switch-paddle-offset: 0.25rem !default;
$switch-paddle-transition-duration: cv.getVar("duration") !default;
$switch-paddle-transition-property: background-color, border-color, opacity, left !default;
$switch-paddle-transition-timing-function: cv.getVar("easing") !default;
$switch-paddle-transition: $switch-paddle-transition-property $switch-paddle-transition-duration $switch-paddle-transition-timing-function !default;
$switch-radius: iv.$radius !default;

@mixin switch-color($color-active: $switch-background-active, $color-inactive: $switch-background) {
    &.is-outlined {
        label {
            background-color: transparent;
            outline-style: solid;
            outline-width: ctrl.$control-border-width;
            outline-color: $color-inactive;
        }

        label::before {
            background-color: $switch-paddle-background;
        }

        input:checked~label {
            outline-color: $color-active;
            background-color: transparent;
        }

        input:checked~label::before {
            background-color: $color-active;
        }
    }

    label {
        background-color: $color-inactive;
    }

    input:checked~label {
        background-color: $color-active;

        &::before {
            background-color: $switch-paddle-background-active;
        }
    }
}

// Mixin for switch size
@mixin switch-size($size: dv.$size-normal) {
    $switch-height: $size * 2;
    $switch-width: $switch-height * 2;
    $paddle-height: $switch-height - ($switch-paddle-offset * 2);
    $paddle-width: $switch-height - ($switch-paddle-offset * 2);
    $paddle-active-offset: $switch-width - $paddle-width - $switch-paddle-offset;

    input:checked~label::before {
        left: $paddle-active-offset;
    }

    label {
        position: relative;
        display: block;
        width: $switch-width;
        height: $switch-height;
        border-radius: $switch-radius;

        &::before {
            width: $paddle-width;
            height: $paddle-height;
            top: $switch-paddle-offset;
            left: $switch-paddle-offset;
            border-radius: $switch-radius;
            background-color: $switch-paddle-background;
            transition: $switch-paddle-transition;
        }

        &::after {
            font-size: $size;
            //height: $paddle-height;
            margin-left: $switch-width + 1rem;
        }
    }

    &.is-rounded {
        label {
            border-radius: math.div($switch-height, 2);

            &::before {
                border-radius: 50%;
            }
        }
    }
}


.switch {
    position: relative;
    display: inline-block;
    margin-bottom: $switch-margin;
    outline: none;
    user-select: none;

    input {
        display: none;
        opacity: 0;
    }

    label {
        opacity: 1;
        display: flex;
        align-items: center;
        text-wrap: nowrap;
        vertical-align: middle;
    }

    label::before,
    label:before {
        position: absolute;
        content: '';
        flex-grow: 0;
        flex-shrink: 0;
        display: flex;
    }

    label::after,
    label:after {
        position: absolute;
        //flex-grow: 1;
        //flex-shrink: 0;
        display: flex;
        align-items: center;
        content: attr(data-label-off);
        //width: 100%;
        height: 100%;
    }

    input:checked~label::after {
        content: attr(data-label-on);
    }

    @include switch-color;
    @include switch-size;
}


@each $name, $color in $switch-colors {
    $color-base: $color;

    @if type-of($color =="list") {
        $color-base: list.nth($color, 1);
    }

    .switch.is-#{$name} {
        @include switch-color($color-base);
    }
}

// Sizes
.switch {
    @include switch-size(dv.$size-normal);
}

.switch.is-small {
    @include switch-size(dv.$size-small);
}

.switch.is-normal {
    @include switch-size(dv.$size-normal);
}

.switch.is-medium {
    @include switch-size(dv.$size-medium);
}

.switch.is-large {
    @include switch-size(dv.$size-large);
}
```

example usage: 

```html
<div class="control is-expanded">
     <div class="switch is-outlined is-rounded">
          <input id="exampleSwitch1" type="checkbox" name="exampleSwitch1">
          <label for="exampleSwitch1" data-label-off="Normal switch off" data-label-on="Normal switch on"></label>
     </div>
</div>
<div class="control is-expanded">
     <div class="switch is-small is-info">
          <input id="exampleSwitch2" type="checkbox" name="exampleSwitch2">
          <label for="exampleSwitch2" data-label-off="Small switch off" data-label-on="Small switch on"></label>
     </div>
</div>
```

I will try to incorporate as much of the :focus (etc) selectors I possibly can into it in the coming days.. Nice job though @jbrazeau
