### ISSUE TITLE
How do I change the background color?

### ISSUE THREAD

**Issue by michrome** [jgthms/bulma#3766]
This is about **the Docs**.

It's a question / I need help.

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs**
I'm using Bulma **version** 1

### Description

I've enjoyed how easy Bulma makes it to lay out my site and am now wanting to customise my colors. I want to use the colors in [Flexoki](https://stephango.com/flexoki) for both light and dark modes and, despite having read through the Bulma docs several times, I'm not sure what's the best way to proceed.

The first thing I want to do is set my text and background colors so I have defined these in my `scss` file as below. The text color is being updated 😀 but the background is not 😢

```scss
/* paper "#FFFCF0" = hsl(48, 100%, 97.06%) */
$flexoki-paper: hsl(48, 100%, 97.06%);
/* black "#100F0F" = hsl(0, 3.23%, 6.08%) */
$flexoki-black: hsl(0, 3.23%, 6.08%);

@use "bulma/sass/utilities/initial-variables" as iv;
@use "bulma/sass/utilities/css-variables" as cv;
@use "bulma/sass/utilities/derived-variables" as dv with (
  $background: $flexoki-paper,
  $text: $flexoki-black
);
@use "bulma/sass/utilities/mixins";
@use "bulma/sass/themes";
@use "bulma/sass/base";
@use "bulma/sass/elements/content";
@use "bulma/sass/grid/columns";
@use "bulma/sass/layout/container";

@include mixins.tablet {
  nav {
    writing-mode: vertical-rl;
  }
}
```

### My specific questions

* Why is this working for text but not for background?
  * How do I update the background?
* What's the best approach I should take to have Flexoki colors for both light and dark modes?
  * Should I be creating a theme?
  * What's the difference between a theme, a color helper and a color palette?
  * I've read the docs but does anyone recommend a guide/further reading elsewhere?

**Comment by michrome** [comment]
Wondering whether a "better" approach for me would be to update the CSS vars directly e.g. I found `--bulma-body-background-color` and `--bulma-scheme-main` but I didn't find a list of CSS vars and their definitions in the docs.

**Comment by digitigradeit** [comment]
Honestly there's a bunch of different ways to change the background color of the page, however, if I was you I would leave $scheme-main and $scheme-invert alone as those are used throughout and 

I think the safest way is to modify $body-background-color, but this would apply the background to both light and dark modes.

```css
$my-awesome-background-color: rgb(0,0,1); // most awesome dark color with ever so slight hint of blue
// Changing the body background-color through *sass/base*
@use "..//node_modules/bulma/sass/base" with (
  $body-background-color: $my-awesome-background-color,
);
```

```css
// Then import the rest using @forweard if not customizing any variables in the corresponding CSS or use @use
@forward "bulma/sass/components/card";
@forward "bulma/sass/components/modal";
@forward "bulma/sass/components/navbar";
@forward "bulma/sass/elements/button";
@forward "bulma/sass/elements/icon";
@forward "bulma/sass/elements/content";
@forward "bulma/sass/elements/notification";
@forward "bulma/sass/elements/progress";
@forward "bulma/sass/elements/tag";
@forward "bulma/sass/layout/footer";
...
```

You *can* also change it through derived-variables, but that wouuld definitely upset the built-in themes mechanism. Changing it through $body-background-color is independent, regardless of light mode or dark mode :) 

You can also change it manually like:


```css
body {
   background-color: rgb(0,0,1);
}
```

And you can of course do it through CSS variables, but sounds like you want to setup a custom bulma theme, rather than rely on the light or dark presets.

But, $background to my understanding is more of a background for menus, panels, buttons, etc.

**Comment by michrome** [comment]
Thanks so much for the detailed reply and advice @digitigradeit. In the end, I went for the 'low tech' option of changing the CSS Variables.


```css
:root {
  --bulma-body-background-color: #fffcf0;
}

@media (prefers-color-scheme: dark) {
  :root {
    --bulma-body-background-color: #100f0f;
  }
}
```
