### ISSUE TITLE
Introduce more Flex utilties

### ISSUE THREAD

**Issue by stsrki** [jgthms/bulma#3768]
I think this is an easy enough change to be worth adding to the library along with other flex utilities.

**Fill:**

```css
.is-flex[-responsive-name]-fill {
    flex: 1 1 auto !important;
}
```

**Order:**

```css
@for $i from 0 through 12 {
    .is-flex-order[-responsive-name]-#{$i} {
        order: $i;
    }
}
```
