### ISSUE TITLE
navbar-padding-vertical not in body scope

### ISSUE THREAD

**Issue by thht** [jgthms/bulma#3772]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [1.0.0]
I am sure this issue is **not a duplicate**.

### Description

When using a navbar with classes `is-fixed-top is-spaced` and thus including `<body class="has-navbar-fixed-top has-spaced-navbar-fixed-top">`, the padding of the navbar is not set correctly.

This is due to the fact that `--bulma-navbar-padding-vertical` ends up in the `.navbar` scope and thus cannot be accessed by

```css
  html.has-spaced-navbar-fixed-top,
  body.has-spaced-navbar-fixed-top {
    padding-top: calc(var(--bulma-navbar-height) + var(--bulma-navbar-padding-vertical) * 2);
  }
```
