### ISSUE TITLE
Message body lost it background if parent use has/is-background-white

### ISSUE THREAD

**Issue by lorrydriveloper** [jgthms/bulma#3775]
This is about **Bulma**.

Having a parent with class background change the behavior of the children's messages body as the variable 
now points to 
```css
[class*=has-background-white], [class*=is-background-white] {
    ...other code
    --bulma-background-l: var(--bulma-white-l);
}
```
that change the 
```css
.message-body {
    background-color: hsl(var(--bulma-message-h), var(--bulma-message-s), var(--bulma-message-background-l));
}
```
that point to 

```css
--bulma-message-background-l: var(--bulma-background-l);
```

### Overview of the problem

I'm using Bulma **version** [1.0] 

### Description

Not sure if it is a bug or an overview, but even in the docs, the class is used. but not having the desired effect anymore.

### Steps to Reproduce

Add has-background-white to any parent where a message is displayed.

### Expected behavior
<img width="992" alt="Screenshot 2024-04-05 at 12 19 25" src="https://github.com/jgthms/bulma/assets/24831929/9113e1fd-87ef-4403-9c4a-1f7815178166">

### Actual behavior
<img width="955" alt="Screenshot 2024-04-05 at 12 19 40" src="https://github.com/jgthms/bulma/assets/24831929/b08b062b-7543-41b8-a3ec-929c0f73921d">
