### ISSUE TITLE
Styling issues on page load (light / dark mode) 

### ISSUE THREAD

**Issue by Ijee** [jgthms/bulma#3880]
This is about **Bulma**.

### Overview of the problem

I'm using Bulma **version** 1.0.2
My **browser** is: Chrome / Firefox

### Description

When I load my website I get some initial stylings I can not get rid of. Because my site uses view-transitions for the routing it looks like this: 

https://github.com/user-attachments/assets/7949e008-2d6c-45de-a192-a98f746c25a3

While I respect the initial user dark mode preferences I set the theme with js on the body like this when the user set it to something else in a previous session.

```
<body class="theme-dark"> 
...
```

The live version of it can be found here: https://develop--amazething.netlify.app/

Maybe I misunderstood how to overwrite the css variables because it sometimes did not change it how I expected it to be so quite a few css rules of mine look like this instead:

```css
body.theme-light {
    background-size: cover;
    background-image: linear-gradient(to top, #95918b 0%, #304352 100%);
}

body.theme-dark {
    background-image: linear-gradient(to top, #1f2229 0%, #304352 100%);
    color: var(--white-dark-87);
}
```
### Steps to Reproduce
I noticed that it also happens on the official bulma.io website on Chrome and Firefox.  This happens when the user's chosen theme doesn't match their system settings (e.g., the user sets light mode but has dark mode enabled in the OS).

https://github.com/user-attachments/assets/ab90550c-a91f-4182-a50a-32bd2d1a0a84

### Expected behavior

The website should not flash from one theme to the other when the user setting does not match the system settings. 

I am not sure if this is a bulma specific problem but at least it also happens on the official website and maybe someone else here knows how to deal with it.
