### ISSUE TITLE
.notification.is-dark.is-dark in official css

### ISSUE THREAD

**Issue by flxmrk** [jgthms/bulma#3911]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [1.0.2]
This is a **Sass** issue: I'm using version [1.0.2]
I am sure this issue is **not a duplicate**

### Description

It would seem there's a sass issue with .notification - as I can't think of any reason why we need `.is-dark.is-dark` which basically makes the text in a dark notification invisible.

As can be seen in https://cdn.jsdelivr.net/npm/bulma@latest/css/bulma.css
```css
.notification.is-light.is-light {
  --bulma-notification-background-l: 90%;
  --bulma-notification-color-l: var(--bulma-light-light-invert-l);
}
.notification.is-light.is-dark {
  --bulma-notification-background-l: 20%;
  --bulma-notification-color-l: var(--bulma-light-dark-invert-l);
}
.notification.is-dark.is-light {
  --bulma-notification-background-l: 90%;
  --bulma-notification-color-l: var(--bulma-dark-light-invert-l);
}
.notification.is-dark.is-dark {
  --bulma-notification-background-l: 20%;
  --bulma-notification-color-l: var(--bulma-dark-dark-invert-l);
}
```

### Steps to Reproduce

Make a notification with just is-dark and you'll see the inner text is also dark.
https://codepen.io/fmp777/pen/BaXNoVg

You probably don't want any of the classes noted above?
