### ISSUE TITLE
Use variable for .content h1,h2 .. font-weight

### ISSUE THREAD

**Issue by tvld** [jgthms/bulma#393]
We now [have](https://github.com/jgthms/bulma/blob/master/sass/elements/content.sass) :
```scss
.content{
 h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    color: $text-strong
    font-weight: 300
}
```
Suggestion to use:
```scss
 font-weight: $weight-title-normal
```
