### ISSUE TITLE
has-icons-right + has-icons-left and RTL

### ISSUE THREAD

**Issue by MetallianFR68** [jgthms/bulma#3981]
In RTL, I think has-icons-right and has-icons-left should be reversed

LTR : 

![Image](https://github.com/user-attachments/assets/ccf26117-4d8b-4f47-959d-68ec672109ed)

RTL : 

![Image](https://github.com/user-attachments/assets/7e415f40-6cde-479c-a0fe-3737bf0326c3)

**Comment by guest20** [comment]
```css
.green-button {
  background-color: red
}
```

**Comment by raydapay** [comment]
**Root cause**

`has-icons-*` looks like the last form helper still using physical `left` / `right`. The rest of v1 has moved to logical properties (`margin-inline-start`, `inset-inline-end`, `padding-inline-start`, `border-inline-*` all appear in the compiled CSS), which is why most components already follow `dir="rtl"`. But here the icon offset and the input padding are pinned to a physical side, so they don't flip.

Current `sass/form/tools.scss` (still the case on `main`):

```scss
&.#{iv.$class-prefix}has-icons-left {
  .#{iv.$class-prefix}input,
  .#{iv.$class-prefix}select select { padding-left: cv.getVar("input-height"); }
  .#{iv.$class-prefix}icon.#{iv.$class-prefix}is-left { left: 0; }
}
&.#{iv.$class-prefix}has-icons-right {
  .#{iv.$class-prefix}input,
  .#{iv.$class-prefix}select select { padding-right: cv.getVar("input-height"); }
  .#{iv.$class-prefix}icon.#{iv.$class-prefix}is-right { right: 0; }
}
```

There are two clean ways to fix this. I've implemented and tested **both** in LTR + RTL, so whichever you prefer, I can open the PR right away.

---

**Option A — convert the existing classes to logical properties (my recommendation).**
Swap the four physical declarations; no new classes, no markup change:

```scss
&.#{iv.$class-prefix}has-icons-left {
  .#{iv.$class-prefix}input,
  .#{iv.$class-prefix}select select { padding-inline-start: cv.getVar("input-height"); }
  .#{iv.$class-prefix}icon.#{iv.$class-prefix}is-left { inset-inline-start: 0; }
}
&.#{iv.$class-prefix}has-icons-right {
  .#{iv.$class-prefix}input,
  .#{iv.$class-prefix}select select { padding-inline-end: cv.getVar("input-height"); }
  .#{iv.$class-prefix}icon.#{iv.$class-prefix}is-right { inset-inline-end: 0; }
}
```

Identical in LTR (`inline-start` resolves to `left`), so it's non-breaking; flips automatically in RTL; matches how the rest of v1 already works. The `left` / `right` names then read as "start" / "end" — the same trade-off v1 already made elsewhere.

**Option B — keep `left` / `right` physical and add logical `has-icons-start` / `has-icons-end`** (with `icon.is-start` / `is-end`) alongside them. Fully additive and non-breaking, but it introduces new classes and two parallel systems.

---

I'd go with **Option A** — smallest change, resolves this directly, and consistent with v1's logical-property direction.

**It's your call though: just say which option you'd prefer (or if you'd rather a different approach), and I'll open the PR.**
