### ISSUE TITLE
How to centered image?

### ISSUE THREAD

**Issue by koddr** [jgthms/bulma#421]
Hello and thanks for awesome Bulma project!

One little question: how to centered `.image` element? I try this:

```html
<figure class="image is-text-centered">
  <img src="http://placehold.it/256x256">
</figure>
```

But it's not work.

P.S. I wish (in future) global element, like `.is-centered`, which make any elements to center aligned (on it's parent's container).

**Comment by anthonygore** [comment]
How did you solve it?

**Comment by koddr** [comment]
@anthonygore simply add this class:

```css
.has-image-centered {
  margin-left: auto;
  margin-right: auto;
}
```
