### ISSUE TITLE
Way to configure stack orders

### ISSUE THREAD

**Issue by shigg1120** [jgthms/bulma#475]
Is there any way to define stack orders on mobile?

For example, take a look at this

[https://jsbin.com/cipayeqepi/edit?html,output](https://jsbin.com/cipayeqepi/edit?html,output)

 It's horizontal on wide screens, when it shrinks "1" is on top.

How can I define an order to make "2" on top in this case.

I also tried to use `order`
[https://jsbin.com/yewifavoyo/edit?html,css,output](https://jsbin.com/yewifavoyo/edit?html,css,output)

**Comment by shigg1120** [comment]
Thanks for the demo.I appreciate that.

But, I was wondering if I can achieve the same result **without** changing a html structure

**Comment by yoostk** [comment]
Ah, OK. That would be something  like this?
You could write it cleaner using mixins though.

```html
<div class="columns reverse-row-order">
  <div class="column box">
    1
  </div>
  <div class="column box">  
    2
  </div>
</div>
```
```css
@media screen and (max-width: 769px) {
  .reverse-column-order {
    display: flex;
    flex-direction: column-reverse;
  }
}
```

https://jsbin.com/xovivuyome/edit?html,css,output
