### ISSUE TITLE
Useful style for migrating forms to 0.4.0

### ISSUE THREAD

**Issue by wolfgang42** [jgthms/bulma#575]
I had a very large form that needed to be migrated from Bulma 0.3 to 0.4. To help with finding all of the incorrect uses of `.control` I wrote the following CSS snippet based on the [blog post about `.field`](http://bulma.io/2017/03/10/new-field-element/):
```css
.control .control, .control .help,
.control.has-addons, .control.is-grouped, .control.is-horizontal, .control-label,
:not(.field)>.control {
	background-color: red;
	box-shadow: 3px 3px 3px 3px red;
}
```
This highlights in red fields that are using the 0.3-style control modifiers. Hopefully this will be of use to other people doing this migration as well.
