### ISSUE TITLE
Hamburger menu icon color

### ISSUE THREAD

**Issue by xereda** [jgthms/bulma#753]
How do I change the color of the hamburger and close icons of sidemenu Bulma?

Tks

**Comment by rowellx68** [comment]
You could do something like this:

CSS
```css
.nav .nav-toggle span {
    background-color: #6a67ce;
}
```

SASS
```sass
.nav {
    .nav-toggle {
        span {
            background-color: #6a67ce;
        }
    }
}
```
