### ISSUE TITLE
table row hover colour is overriding table row is-selected colour

### ISSUE THREAD

**Issue by shongololo** [jgthms/bulma#822]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.4.1
My **browser** is: Chrome  59.0.3071.86
I am sure this issue is **not a duplicate**?

### Description

The table hover colour is overriding the table row selected colour. i.e. when a table row is selected with the is-selected style modifier, the hover colour will still apply, which makes the text illegible. 

Workaround for now by adding:
```scss
.table {
        tr {
            &.is-selected:hover {
                background: $primary;
            }
        }
    }
```

### Steps to Reproduce

1. Create a bulma table
2. Apply is-selected to a row
3. Hover over the selected row.

### Expected behavior

The hover colour shouldn't override the selected colour.

### Actual behavior

The hover colour overrides the selected colour.
