### ISSUE TITLE
is-loading on any element ?

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#847]
Hi,

How can I use the is-loading modifier (available for buttons) on any type of element ?
For example when loading a div content, ....

Regards

**Comment by rafaelpimpa** [comment]
I've done this for a component, you can get from here:

```scss
.element {
    &.is-loading {
        position: relative;
        pointer-events: none;
        opacity: 0.5;
        &:after {
            @include loader;
            position: absolute;
            top: calc(50% - 2.5em);
            left: calc(50% - 2.5em);
            width: 5em;
            height: 5em;
            border-width: 0.25em;
        }
    }
}
```
