### ISSUE TITLE
Feature: fieldset and legend tags styles

### ISSUE THREAD

**Issue by mdesantis** [jgthms/bulma#886]
### Feature: fieldset and legend tags styles

This is about the Bulma **CSS framework**
I'm using Bulma **0.4.3**
I am sure this issue is **not a duplicate**

### Description

At the moment, `fieldset` and `legend` HTML tags are unstyled, so they look ugly. They are not so used elements at the moment, but they are still quite important in admin forms.

At the moment I'm using this, which isn't too bad:

```sass
.fieldset
  @extend .box
  border: 0 none
  > legend
    @extend .label
    padding: 0 5px
```

### Steps to Reproduce

1. Write this inside an HTML page using Bulma:
```html
<fieldset class="fieldset">
  <legend>Legend</legend>
</fieldset>
```
2. Look at it

### Expected behavior

It doesn't look ugly

### Actual behavior

It looks ugly

**Comment by Potherca** [comment]
I had the same issue, using the HTML below gave an okay result:

```html
<fieldset class="box">
  <legend class="label has-text-centered">Legend</legend>
  <!-- ... -->
</fieldset>
```

**Comment by danswiser** [comment]
If done the same however the following felt neater to me:

`<legend class="subtitle is-3">Legend</legend>`

**Comment by Cethy** [comment]
Adding `content` to fieldset class adds the right padding.

**Comment by james-wasson** [comment]
This is what I have currently:
```SASS
fieldset.box > legend
  padding: 0 2px
  background-repeat: no-repeat
  background-image: linear-gradient(transparent calc(50% - 1px), $box-color calc(50% - 1px))
```
The issue being that the box shadow variable is defined like:
```SASS
$box-shadow: 0 2px 3px rgba($black, 0.1), 0 0 0 1px rgba($black, 0.1) !default
```
So the `1px` offset will not always be enough to handle this case.
I could always add `position: absolute` and move the `legend` around but I'm not sure that's the best solution.
@jgthms any thoughts?

**Comment by oupala** [comment]
No particular thought for me. I'm not an expert enough to tell what is the best solution. Sorry...

**Comment by anejjar** [comment]
# HTML
``` html
<fieldset class="fieldset">
     <legend>legend</legend>
</fieldset>
```
# CSS
``` css
.fieldset{
   background-color: #fff;
    border-radius: 6px;
    box-shadow: 0 0.5em 1em -0.125em rgba(10,10,10,.1), 0 0 0 1px rgba(10,10,10,.02);
    color: #4a4a4a;
    display: block;
    padding: 1.25rem;
   border: 1px solid #ccc
}
.fieldset  > legend{
    color: #363636;
    display: block;
    font-size: 1rem;
    font-weight: 700;
    background-color: #fff;
    padding: 0 5px;
	width: max-content;
	border: 0 none
}
```
# result 
![Sans titre](https://user-images.githubusercontent.com/31830418/68212844-aa805000-ffda-11e9-9356-07071199ee77.png)
